### ISSUE TITLE
[improvement] Secure or document which endpoints to not publicly serve

### ISSUE THREAD

**Issue by stayallive** [soketi/soketi#124]
Right now `/usage` & `/metrics` (if enabled) are publicly available if you run the server.

Although they don't seem like an issue to open up, it would probably be better to keep these private or at least internal.

There are a few routes that come to mind:

- Run those endpoints on another "internal" port and keep 6001 as the "public" server
- Add some kind of simple authentication token that needs to be passed as header/query to the endpoint before they respond
- Document that those endpoints exists and that you might not want to expose them publicly

I'm not 100% what the best route here would be, but figured I put my thoughts here to start the discussion.

**Comment by rennokki** [comment]
Managed to do that, will deploy a new version for it, after I update the docs. :)

**Comment by stayallive** [comment]
Nice, looks great 👌
