### ISSUE TITLE
[feature] MySQL 8 support  

### ISSUE THREAD

**Issue by mwangaben** [soketi/soketi#142]

**Comment by rennokki** [comment]
Hi, what are exactly your needs? soketi is already tested against MySQL 8.x

**Comment by mwangaben** [comment]
I am on MYSQL 8.0.15. and when i use mysql driver as APP_MANAGER_DRIVER this is what i get on the terminal


`(node:27139) UnhandledPromiseRejectionWarning: Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (/usr/local/lib/node_modules/@soketi/pws/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)`

**Comment by rennokki** [comment]
This can be fixed by specifying `APP_MANAGER_MYSQL_USE_V2`:

```bash
$ APP_MANAGER_MYSQL_USE_V2=1 soketi start
```
