### ISSUE TITLE
How to keep Soketi alive?

### ISSUE THREAD

**Issue by francoism90** [soketi/soketi#148]
Thanks for creating this package, going to try as Laravel Websockets replacement which seems to be unmaintained. :)

I was browsing the documentation (which need a fix for the Github repo link btw.) and I was wondering what you think is the best solution to keep the (socket) process alive? I'm using Supervisor, but as this is a NPM solution it may require something different?

**Comment by rennokki** [comment]
Supervisor is okay to run the app with. Just replace the command that needs to be run with `soketi start`.
