### ISSUE TITLE
Subscribe and unsubscribing events

### ISSUE THREAD

**Issue by jsandfordhughes** [soketi/soketi#172]
Hey there, 

Is there a way for the server to only send subscribing and unsubscribing events for the same user once? 
So if the same user subscribes to a private channel from 3 devices it only sends the subscribing event for the first device connected and then only sends the unsubscribe event once when the last client disconnects? 

Thanks

Joe

**Comment by rennokki** [comment]
Well, that's a bit of a problem here. I planned on working on https://github.com/soketi/soketi/pull/19 a while back but had to push it down for some other priorities. The idea is that as long as the user_id exists in the presence channel, it shouldn't emit added events. Same with the exit, it shouldn't emit removed events if the user is still connected from other devices. That's a bit vague reply, but it's WIP and I need to find a good way to implement it.

**Comment by audiojames** [comment]
Did you come across any problems with #19?  I am happy to continue working on it.  It looks like a similar solution to this will work here: https://github.com/beyondcode/laravel-websockets/pull/530/

**Comment by rennokki** [comment]
Fixed in [0.18.0](https://github.com/soketi/soketi/releases/tag/0.18.0)
