### ISSUE TITLE
[question] How to change listening host?

### ISSUE THREAD

**Issue by GlitchesIT** [soketi/soketi#192]
Sorry if this is a dumb question, but I'm trying to set up soketi on a test server in our environment.  Using Laravel 8 pusher replacement with Echo and Vue.  Setup for local dev with the sail container, and it works great.  

On the server though, not so much.  Got it working with the self-signed cert using the workarounds, and supervisor indicates that soketi is running.  Used the CLI install.

However, I'm not sure what env variables to set in order to change the listening host (logs indicate it's running at 127.0.0.1, but Vue is trying to connect to 127.0.0.1, which obviously didn't work).  So I changed that to https://my.server.url, which results in a 404.

Is there a list somewhere of all the .env variables socketi itself can use?  Would like to change the app ID/pw, listening URL, etc.

Any help would be greatly appreciated.  Thanks!

**Comment by rennokki** [comment]
The host is by default `localhost`. For custom hosts, consider using a reverse proxy like NGINX or HAProxy. I don't have an example config right now, but you may use some Laravel WebSockets [NGINX config example](https://gist.github.com/angelside/f2899cf2ab17ffb9d619889dce4492ac#step6---nginx-virtual-host-example), it works likewise.

**Comment by GlitchesIT** [comment]
Thanks for the response - I appreciate you taking the time to answer.  I'll look into those.

For anyone else wondering about the rest, I found the array driver documentation, which allowed me to change several of the basic keys I needed to in this environment:

https://rennokki.gitbook.io/soketi-docs/app-management/array-driver
