### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by ricocrivelli** [soketi/soketi#204]
I'm getting this message when I try to install the package:

```
npm install -g @soketi/soketi
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/uNetworking/uWebSockets.js.git
npm ERR! command-line line 0: unsupported option "accept-new".
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-13T18_15_10_616Z-debug-0.log
```

Can someone help-me?

**Comment by rennokki** [comment]
One of the packages is [served via Github](https://github.com/soketi/soketi/blob/66b90ad65e4ee3ca5ab493397dbf8c11be307314/package.json#L46) instead of the usual NPM registry, so having SSH is a must in the installation process. You can [try and mitigate this to make NPM install the package via HTTPS instead of SSH](https://stackoverflow.com/questions/61051073/npm-install-from-git-use-https-instead-ssh)

**Comment by eosvn** [comment]
Hi, I got the same error when installing the package on Ubuntu server 18.04. Tried many ways, but it is not fixed.

**Comment by ricocrivelli** [comment]
Hi, I've give up using this package.

I tried everything I know, but I get no success. =(

*Ricardo Crivelli*


Em sáb., 18 de dez. de 2021 às 05:40, Be Duc Tai ***@***.***>
escreveu:

**Comment by eosvn** [comment]
@ricocrivelli Yes, I was expecting a fast WebSocket server. I also gave up, still using socket.IO.

**Comment by ricocrivelli** [comment]
I'm using Ably, as I need to put my app working ASAP.

I'll try to find how to use socket.IO with channels like Pusher.

As my backend is using Laravel, I'm considering using Laravel Websockets (
https://beyondco.de/docs/laravel-websockets/getting-started/installation)

*Ricardo Crivelli*


Em sáb., 18 de dez. de 2021 às 17:45, Be Duc Tai ***@***.***>
escreveu:

**Comment by eosvn** [comment]
Yes, Socket.io it's not as easy as Pusher or Ably, to use a channel like Pusher you would use *room* as something instead.

**Comment by rennokki** [comment]
@eosvn @ricocrivelli Just tried to install this command on a fresh Ubuntu distro and did not get any issue. Have you tried installing ssh & git on the instance?

```bash
apt install -y git ssh
```

**Comment by ricocrivelli** [comment]
I'm using a CentOS 7 VPS server at Hostgator. I don't have the option to
update or change the OS.

*Ricardo Crivelli*


Em dom., 19 de dez. de 2021 às 09:19, rennokki ***@***.***>
escreveu:

**Comment by rennokki** [comment]
@ricocrivelli Installing git on the virtual machine fixed the issue. This was on both CentOS 7 and CentOS 8.

Make sure to also `yum update` before installing the git:

```sh
yum install git
```

However, I found out there are issues with the RHEL distribution, so I need to investigate more. :)

**Comment by rennokki** [comment]
@ricocrivelli uWebSockets.js does not support old distros of RHEL: https://github.com/uNetworking/uWebSockets.js/discussions/218

**Comment by eosvn** [comment]
> @eosvn @ricocrivelli Just tried to install this command on a fresh Ubuntu distro and did not get any issue. Have you tried installing ssh & git on the instance?
> 
> ```shell
> apt install -y git ssh
> ```

Really like the idea of soketi. But try this does not work.

**Comment by rennokki** [comment]
@eosvn Which provider did you choose? Tried a fresh 18.04 on Scaleway and it didn't have any issues. 👀

**Comment by eosvn** [comment]
@rennokki I'm using EC2 on AWS
Tried
```
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/uNetworking/uWebSockets.js.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-19T16_22_19_734Z-debug-0.log
```

**Comment by rennokki** [comment]
@eosvn Can you pass the EC2 AMI you're currently using? It doesn't have to contain your server data, just to be as close as possible to your current config so I can investigate what's not working.

**Comment by eosvn** [comment]
> @eosvn Can you pass the EC2 AMI you're currently using? It doesn't have to contain your server data, just to be as close as possible to your current config so I can investigate what's not working.

I will try installing with a new VPS. I'll let you know if there's a problem. Thank you!

**Comment by rennokki** [comment]
Sure, let me know if the issue still persists.

**Comment by Midblep** [comment]
Hello I'm running into the same problem. How was this fixed?

**Comment by abewartech** [comment]
same problem here

`npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/uNetworking/uWebSockets.js.git
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-06T10_40_22_518Z-debug-0.log`

**Comment by eosvn** [comment]
Hi @abewartech @Midblep @ricocrivelli @rennokki I fixed this problem on Ubuntu 18.04
Yeah, it's working very good :))

**Comment by jonathanpmartins** [comment]
> Hi @abewartech @Midblep @ricocrivelli @rennokki I fixed this problem on Ubuntu 18.04 Yeah, it's working very good :))

How did you solved it @eosvn? 

git and ssh are installed:
```
sudo apt install -y git ssh
```

Running the following command with sudo does not install soketi:
```
sudo npm install -g @soketi/soketi
```
I get the same log as @abewartech described.

The only way that I could install soketi was making login with root like:
```
sudo -i;
npm install -g @soketi/soketi
```

Is it safe to install soketi like that @rennokki?

**Comment by eosvn** [comment]
@jonathanpmartins Because of my problem when installing is "npm ERR! Permission denied (publickey)."
We need to be generated an SSH key. Then add publickey to "User Menu" >> "Settings" >> "SSH and GPG keys" (https://github.com/settings/keys) Next click "New SSH key" button, paste publickey input.
```
npm install -g @soketi/soketi
```

**Comment by chrisgo** [comment]
This may help if you are manually installing (not if you are using fabric or ansible)

```
sudo su -
npm install -g @soketi/soketi
```

so you switch to the root user first then run npm install
