### ISSUE TITLE
How to use the REST API?

### ISSUE THREAD

**Issue by w95** [soketi/soketi#222]
How to authenticate on these endpoints?

- /apps/:appId/channels
- /apps/:appId/channels/:channelName
- /apps/:appId/channels/:channelName/users
- /apps/:appId/events

**Comment by rennokki** [comment]
What language you're trying to implement your backend client on?

You would want to use Pusher's SDK for your language: https://pusher.com/docs/channels/server_api/overview/
In addition to this, for the SDK you're using, you should point the host and port to the soketi's IP & port `6001` by default.

**Comment by w95** [comment]
Thank you!
