### ISSUE TITLE
Webhooks not being processed when using Redis?

### ISSUE THREAD

**Issue by stayallive** [soketi/soketi#227]
So I am basically seeing what #66 is seeing... when using the Redis queue worker webhooks are not being processed.

I have been pulling my hair out all night trying to figure this out and adding `console.log` everywhere I can think of... it looks like the queue workers are started and events are queue in Redis but they are not being processed for some reason... they just build up in Redis (I'm checking with an Redis client) never being sent, the queue callback is never executed.

If you have any clue what I can try or how I can debug that would be awesome!

(switching queue driver to `sync` works like a charm, so config is good)

**Comment by rennokki** [comment]
[I think this is the issue](https://github.com/soketi/soketi/blob/45ed9761c353dd384408e934f78bea324b67f27c/src/queues/redis-queue-driver.ts#L38)

**Comment by rennokki** [comment]
For a moment I thought that bullmq processes the queues differently by job name. But it seems like job names do not inflict anything. It's a configuration issue somewhere. Have you triggered the job without a prefix or something?

**Comment by stayallive** [comment]
Damn. I found it 😅 

> Delayed jobs will only be processed if there is at least one QueueScheduler instance configured in the Queue.
> https://docs.bullmq.io/guide/jobs/delayed

These are our default job options `defaultJobOptions: { attempts: 6, delay: 1000 },`.

So because of the delay and not having a `QueueScheduler` they are never ever processed :)

I'll cook up a PR to set some other option as the default!
