### ISSUE TITLE
Scrollbar flickering on certain screen sizes

### ISSUE THREAD

**Issue by markwalet** [soketi/soketi#240]
When the screen has a certain size, the page starts flickering.

I tested this on Chrome and Firefox. Both had the problem.

From what I could see: The problem occurs on the desktop version of the site. When the height of the browser window is just as long as the website, the

 scrollbar keeps appearing and disappearing, which moves the content of the page.

https://user-images.githubusercontent.com/11446771/148048343-4e763648-e5d1-4fea-b89a-e80980c9b0d5.mov

**Comment by rennokki** [comment]
This is a Gitbook issue. I'll forward this to them 😁
