### ISSUE TITLE
 WebSocket connection failed  - Laravel 8 + pusher-php-server 7.0

### ISSUE THREAD

**Issue by farshidpg** [soketi/soketi#279]
I install soketi and change my config to : 

broadcasting.php >

```
 'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'host' => env('PUSHER_HOST', '127.0.0.1'),
                'port' => env('PUSHER_PORT', 6001),
                'scheme' => env('PUSHER_SCHEME', 'http'),
                'encrypted' => true,
                'useTLS' => env('PUSHER_SCHEME') === 'https',
            ],
```

FrontEnd : 

```
window.Echo = new Echo({
        broadcaster: 'pusher',
        key: process.env.MIX_PUSHER_APP_KEY,
        cluster: process.env.MIX_PUSHER_APP_CLUSTER,
        forceTLS: process.env.MIX_PUSHER_FORCE_TLS,
        encrypted: true,
        wsHost: process.env.MIX_PUSHER_HOST,
        wsPort: process.env.MIX_PUSHER_PORT,
        wssPort: process.env.MIX_PUSHER_PORT,
        disableStats: true,
        enabledTransports: ["ws", "wss"],
    });
```

.env  = 

```

PUSHER_APP_ID=app-id
PUSHER_APP_KEY=app-key
PUSHER_APP_SECRET=app-secret
PUSHER_APP_CLUSTER=ap2

PUSHER_HOST=127.0.0.1
PUSHER_PORT=6001
PUSHER_SCHEME=http

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_HOST="${PUSHER_HOST}"
MIX_PUSHER_PORT="${PUSHER_PORT}"
MIX_PUSHER_FORCE_TLS=false
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
MIX_PUSHER_SERVICE="${PUSHER_SERVICE}"

```

and all of this run successfull

NPM RUN WATCH  ==== success

php artisan serve  === success http://127.0.0.1:8000

soketi start  ==== success http://127.0.0.1:6001/  => response " OK"

but  in the console my app cant connect to the websocket

![Screenshot 2022-01-11 004137](https://user-images.githubusercontent.com/9290073/148840072-6d5a1868-b230-42d7-a5e1-7f162bf449fc.png)

**Comment by rennokki** [comment]
It seems like your frontend app uses `ws` transport (which is correct), but somehow the `forceTLS` seems to be `true`. I think you misconfigured something.

**Comment by farshidpg** [comment]
I use private chanels with pusher i see “auth”  request in console network tab . Is possible my problem from using private chanel ?

**Comment by farshidpg** [comment]
i found my problem 

forceTLS: process.env.MIX_PUSHER_FORCE_TLS,

 that set false in .env not proccess i dont know why !!!

 i set false  in hard code
 
 forceTLS: false

and all thing is ok , but why set false in env not working ??

**Comment by osbre** [comment]
@farshidpg It is likely that you had to restart the build process after making changes to `.env`. (sometimes we have to reload it)

(that was the solution in my case)

**Comment by qurius** [comment]
Please use encrypted = false in local environment
