### ISSUE TITLE
[bug] Server crashes while benchmarking with Artillery

### ISSUE THREAD

**Issue by wjstraver** [soketi/soketi#286]
Hi, 

### The problem
I was testing this project with Artillery to see how much connections and messages is could handle, but the server kept on crashing on me. I used the following config for artillery:

```yaml
config:
  target: "ws://localhost:6001/app/app_key?protocol=7&client=js&version=7.0.3&flash=false"
  phases:
    - duration: 30
      arrivalRate: 10
scenarios:
  - engine: "ws"
    flow:
      - send: '{"event":"pusher:subscribe","data":{"auth":"","channel":"chanel_name"}}'  # Subscribe to the public channel
      - think: 60 # Every connection will remain open for 15s
```

With this, every 10 seconds, 30 new clients will connect and stay connected for 60 seconds. The subscribe event to a channel is what I needed to test messages (by sending them from another script).

However, every time I started, the server crashes with the following error:
```log
/Users/[app_path]/node_modules/@soketi/soketi/dist/channels/public-channel-manager.js:11
        return this.server.adapter.getNamespace(ws.app.id).addToChannel(ws, channel).then(connections => {
                                                       ^

TypeError: Cannot read property 'id' of undefined
    at PublicChannelManager.join (/Users/[app_path]/node_modules/@soketi/soketi/dist/channels/public-channel-manager.js:11:56)
    at WsHandler.subscribeToChannel (/Users/[app_path]/node_modules/@soketi/soketi/dist/ws-handler.js:233:24)
    at WsHandler.onMessage (/Users/[app_path]/node_modules/@soketi/soketi/dist/ws-handler.js:121:22)
    at message (/Users/[app_path]/node_modules/@soketi/soketi/dist/server.js:345:68)
```

### The cause

After some testing and digging, I've discovered that my test script for Artillery sends the `pusher:subscribe` event before the connection is fully established. Normally the connection log will look something like this:

```log
[Sat Jan 15 2022 17:01:18 GMT+0100 (Central European Standard Time)] 👨‍🔬 New connection:
{
  ws: uWS.WebSocket {
    ip: '127.0.0.1',
    ip2: '',
    appKey: 'app_key'
  }
}
[Sat Jan 15 2022 17:01:18 GMT+0100 (Central European Standard Time)] ✈ Sent message to client:
{
  ws: uWS.WebSocket {
    ip: '127.0.0.1',
    ip2: '',
    appKey: 'app_key',
    sendJson: [Function (anonymous)],
    id: '2037856788.7732658047',
    subscribedChannels: Set(0) {},
    presence: Map(0) {},
    app: App {
      id: 'app_name',
      key: 'app_key',
      secret: 'app_secret',
      //..
    },
    timeout: //..
  },
  data: {
    event: 'pusher:connection_established',
    data: '{"socket_id":"2037856788.7732658047","activity_timeout":30}'
  }
}
[Sat Jan 15 2022 17:01:18 GMT+0100 (Central European Standard Time)] ⚡ New message received:
{
  message: {
    event: 'pusher:subscribe',
    data: {
      auth: '',
      channel: '[channel_name]'
    }
  },
  isBinary: false
}

```
As you can see the Websocket interfase has an `app` property which contains an id, key, secret etc.

However, with artillery the log looks as follows:
```log
[Sat Jan 15 2022 16:59:23 GMT+0100 (Central European Standard Time)] 👨‍🔬 New connection:
{
  ws: uWS.WebSocket {
    ip: '127.0.0.1',
    ip2: '',
    appKey: 'app_key'
  }
}
[Sat Jan 15 2022 16:59:23 GMT+0100 (Central European Standard Time)] ⚡ New message received:
{
  message: {
    event: 'pusher:subscribe',
    data: {
      auth: '',
      channel: '[channel_name]'
    }
  },
  isBinary: false
}

```

It misses the `pusher:connection_established` messages from the server to the client and as you can see the Websocket interface does not yet have a `app` property before it receives a `pusher:subscribe` event. Because of this the app crashes, since it expects the `app` property when handling the subscribe event.

### Possible solution

First solution from my side is very simple: wait with Artillery for the `pusher:connection_established` event before sending data. This works. However, I don't think the server should crash when you do by accident send data from a client before this.

Maybe adding something like the following to `dist/ws-handler.js` at line 256 (version: `0.26.3` of soketi)

```javascript
channelManager.join(ws, channel, message).then((response) => {
            if (!response.success) {
                // ..
            }
            // fix example
            if(!ws.app) {
                return ws.sendJson({
                        event: 'pusher:subscription_error',
                        channel,
                        data: {
                            type: 'ConnectionError',
                            error: "Subscribe request sent before connection fully established. Wait for connection to be completed",
                            status: 405,
                        },
                    });
            }
            // end fix example
            if (!ws.subscribedChannels.has(channel)) {
                ws.subscribedChannels.add(channel);
            }
            this.server.adapter.getNamespace(ws.app.id).addSocket(ws);
            // ..
}
```

Some other places I think the app can crash because of the same issue are at the following methods:
- `unsubscribeFromChannel()` at line 321
- `handleClientEvent()` at line 354
- `checkAppConnectionLimit()` at line 431

I hope this is helpful for your awesome project!

**Comment by wjstraver** [comment]
One thing for context: I use MySQL as App Driver. Probably that is one of the reasons why the Websocket interface does not have the app property directly when the connection is made (I would guess getting the app data from the database will take a couple of milliseconds)

**Comment by rennokki** [comment]
This is the usual issue if Pusher SDK is not used, and the [Pusher Protocol](https://pusher.com/docs/channels/library_auth_reference/pusher-websockets-protocol/#pusherconnection_established-pusher-channels-greater-client) is actually specifying to not send anything to the server until the `pusher:connection_established` is received.

I can only implement your fix idea, which IMO it should be in-place, at least to help troubleshoot non-Pusher SDK users with their implementation.
