### ISSUE TITLE
cURL error 7: Failed to connect to 127.0.0.1 port 6001: Connection refused

### ISSUE THREAD

**Issue by ivancelot** [soketi/soketi#319]
cURL error 7: Failed to connect to 127.0.0.1 port 6001: Connection refused.

![image](https://user-images.githubusercontent.com/5238400/151722469-657f97f8-f17b-4d4a-972f-4c129d9b9d73.png)

![image](https://user-images.githubusercontent.com/5238400/151722484-88803af4-d252-407b-a522-46ef18d64712.png)

**Comment by rennokki** [comment]
You need to put the following variables in your `.env` file:

```
PUSHER_HOST=soketi
PUSHER_APP_ID=app-id
PUSHER_APP_KEY=app-key
PUSHER_APP_SECRET=app-secret
```

That's because the `127.0.0.1` address is not pointing to soketi, but `soketi` is automatically resolved to the server. Docker stuff.
