### ISSUE TITLE
Is there any logs to see connections etc.. 

### ISSUE THREAD

**Issue by hallowcard13** [soketi/soketi#331]
Hi  installed using docker image, is there any log file i can see the connections or channels ?

**Comment by rennokki** [comment]
`DEBUG=1` variable

**Comment by hallowcard13** [comment]
I already added that on my .env ,How can i see it if im running it using docker

**Comment by rennokki** [comment]
`docker run ... -e DEBUG=1 -p 6001:6001 ..."

You should not run it with `-d` to be able to see the container's logs.

**Comment by hallowcard13** [comment]
@rennokki  thank you, one last time, any tips on how i can subscribe to private channels ?
