### ISSUE TITLE
How Will i know if client is  already subscribe to a private channel ? 

### ISSUE THREAD

**Issue by hallowcard13** [soketi/soketi#333]
Currently  this is on my console.

![Screen Shot 2022-02-03 at 1 49 27 PM](https://user-images.githubusercontent.com/4696933/152288520-d5c5f003-84b8-4bff-a40e-09b8703071a3.png)

and this is the event sent from laravel broadcast event

![Screen Shot 2022-02-03 at 1 49 49 PM](https://user-images.githubusercontent.com/4696933/152288568-efd0be1c-163e-4d1d-82d2-af986c1a6913.png)

 Unfortunately client doesn't receive the data . Any tips.

Im Using 
Laravel 8
Nuxt

**Comment by micos7** [comment]
![channels](https://user-images.githubusercontent.com/4460809/152863467-a721a7b6-a947-4036-bc8c-241233415598.png)
It should look live above,take a glance here also https://github.com/soketi/soketi/issues/343

**Comment by japr8985** [comment]
I have had the same problem. When the letters in the soketi console appear in blue the client does not receive information. [#343](https://github.com/soketi/soketi/issues/343). I already tried this option and it didn't work for me

**Comment by rennokki** [comment]
Open your Developer Tools in your browser and watch the WebSockets messages. They will give you the right information wether you're subscribed or not.
