### ISSUE TITLE
[bug] Prioritize `SOKETI_*` variables over others.

### ISSUE THREAD

**Issue by rbruhn** [soketi/soketi#340]
I would like to suggest using SOKETI_ for environment variables as your current variables some times conflict with existing ones.
For example, I use Beanstalk for a queue in Laravel to processing some heavy jobs. Soketi sees that and fails. Instead, I have to alter my Laravel queue.php file and change QUEUE_DRIVER to something like LARAVEL_QUEUE_DRIVER.

Of course, it works and is easy to change in my case, but might be avoidable with SOKETI_ distinction.

**Comment by rennokki** [comment]
They are looking for [`SOKETI_*` variables](https://github.com/soketi/soketi/blob/master/src/cli/cli.ts#L125) in the code.
