### ISSUE TITLE
Needs help with laravel + soketi

### ISSUE THREAD

**Issue by blitzen12** [soketi/soketi#350]
Hello, I'm only beginner in setting up laravel + websockets and I have come across this great package.

I saw an example from [here](https://github.com/soketi/laravel-chat-app?ref=https://githubhelp.com) and I thought it might be a great way for me to learn so I downloaded it at follow the instructions however I can't seem to get it work.

I have added `SOKETI_DEBUG=1` in my `.env` file and run `soketi start`. 
`{
          adapter: {
            driver: 'local',
            redis: { prefix: '', redisOptions: {}, clusterMode: false }
          },
          appManager: {
            driver: 'array',
            array: {
              apps: [
                {
                      id: 'app-id',
                      key: 'app-key',
                      secret: 'app-secret',
                      maxConnections: -1,
                      enableClientMessages: false,
                      enabled: true,
                      maxBackendEventsPerSecond: -1,
                      maxClientEventsPerSecond: -1,
                      maxReadRequestsPerSecond: -1,
                      webhooks: []
                }
              ]
            },
            dynamodb: { table: 'apps', region: 'us-east-1', endpoint: null },
            mysql: { table: 'apps', version: '8.0', useMysql2: false },
            postgres: { table: 'apps', version: '13.3' }
          },
          channelLimits: { maxNameLength: 200 },
          cluster: {
                host: '0.0.0.0',
                helloInterval: 500,
                checkInterval: 500,
                nodeTimeout: 2000,
                masterTimeout: 2000,
                port: 11002,
                prefix: '',
                ignoreProcess: true
          },
          cors: {
                credentials: true,
                origin: [ '*' ],
                methods: [ 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS' ],
                allowedHeaders: [
                      'Origin',
                      'Content-Type',
                      'X-Auth-Token',
                      'X-Requested-With',
                      'Accept',
                      'Authorization',
                      'X-CSRF-TOKEN',
                      'XSRF-TOKEN',
                      'X-Socket-Id'
                ]
          },
          database: {
                mysql: {
                      host: '127.0.0.1',
                      port: 3306,
                      user: 'root',
                      password: 'password',
                      database: 'main'
                },
                postgres: {
                      host: '127.0.0.1',
                      port: 5432,
                      user: 'postgres',
                      password: 'password',
                      database: 'main'
                },
                redis: {
                      host: '127.0.0.1',
                      port: 6379,
                      db: 0,
                      username: null,
                      password: null,
                      keyPrefix: '',
                      sentinels: null,
                      sentinelPassword: null,
                      name: 'mymaster',
                      clusterNodes: []
                }
          },
          databasePooling: { enabled: false, min: 0, max: 7 },
          debug: 1,
          eventLimits: {
                maxChannelsAtOnce: 100,
                maxNameLength: 200,
                maxPayloadInKb: 100,
                maxBatchSize: 10
          },
          httpApi: { requestLimitInMb: 100, acceptTraffic: { memoryThreshold: 85 } },
          instance: { process_id: 99375 },
          metrics: {
                enabled: false,
                driver: 'prometheus',
                prometheus: { prefix: 'soketi_' },
                port: 9601
          },
          mode: 'full',
          port: 6001,
          pathPrefix: '',
          presence: { maxMembersPerChannel: 100, maxMemberSizeInKb: 2 },
          queue: {
                driver: 'sync',
                redis: { concurrency: 1, redisOptions: {}, clusterMode: false },
                sqs: {
                  region: 'us-east-1',
                  endpoint: null,
                  clientOptions: {},
                  consumerOptions: {},
                  queueUrl: ''
                }
          },
          rateLimiter: { driver: 'local', redis: { redisOptions: {}, clusterMode: false } },
          shutdownGracePeriod: 3000,
          ssl: { certPath: '', keyPath: '', passphrase: '', caPath: '' },
          webhooks: { batching: { enabled: false, duration: 50 } }
}

📡 soketi initialization....

⚡ Initializing the HTTP API & Websockets Server...

⚡ Initializing the Websocket listeners and channels...

⚡ Initializing the HTTP webserver...

🕵️‍♂️ Initiating metrics endpoints...

🎉 Server is up and running!

📡 The Websockets server is available at 127.0.0.1:6001

🔗 The HTTP API server is available at http://127.0.0.1:6001

🎊 The /usage endpoint is available on port 9601.

[Thu Feb 10 2022 16:20:15 GMT+0800 (Philippine Standard Time)] New node added.
{
      isMaster: true,
      isMasterEligible: true,
      weight: -0.1644396668208,
      address: '120.100.0.63',
      lastSeen: 1644481215801,
      hostName: 'APM3LC02CK2HVMD6R',
      port: 11002,
      id: 'c473d932-8a16-4600-a190-df450ea79b7d'
}
[Thu Feb 10 2022 16:20:15 GMT+0800 (Philippine Standard Time)] New master.
{
      isMaster: true,
      isMasterEligible: true,
      weight: -0.1644396668208,
      address: '120.100.0.63',
      lastSeen: 1644481215801,
      hostName: 'APM3LC02CK2HVMD6R',
      port: 11002,
      id: 'c473d932-8a16-4600-a190-df450ea79b7d'
}`

However when I tried to send a message after logging in. I this exception.

`[2022-02-10 08:21:36] laravel.ERROR: Pusher error: {"error":"Unauthorized"}. {"userId":1,"exception":"[object] (Illuminate\\Broadcasting\\BroadcastException(code: 0): Pusher error: {\"error\":\"Unauthorized\"}. at /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php:128)
[stacktrace]
#0 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php(77): Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster->broadcast(Array, 'room.message', Array)
#1 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Broadcasting\\BroadcastEvent->handle(Object(Illuminate\\Broadcasting\\BroadcastManager))
#2 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#4 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#5 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#6 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call(Array)
#7 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Illuminate\\Broadcasting\\BroadcastEvent))
#8 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Broadcasting\\BroadcastEvent))
#9 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#10 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastManager.php(119): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Illuminate\\Broadcasting\\BroadcastEvent))
#11 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(320): Illuminate\\Broadcasting\\BroadcastManager->queue(Object(App\\Events\\Message))
#12 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(243): Illuminate\\Events\\Dispatcher->broadcastEvent(Object(App\\Events\\Message))
#13 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Broadcasting/PendingBroadcast.php(72): Illuminate\\Events\\Dispatcher->dispatch('App\\\\Events\\\\Mess...')
#14 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Foundation/Events/Dispatchable.php(52): Illuminate\\Broadcasting\\PendingBroadcast->__destruct()
#15 /Users/blitzen12/Workspace/laravel-chat-app/app/Http/Controllers/SendMessageController.php(27): App\\Events\\Message::broadcast(Object(App\\Models\\User), '6YVhPCCCTA', 'ddd')
#16 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\SendMessageController->__invoke(Object(Illuminate\\Http\\Request))
#17 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('__invoke', Array)
#18 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\SendMessageController), '__invoke')
#19 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#20 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#21 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Auth/Middleware/EnsureEmailIsVerified.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\EnsureEmailIsVerified->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /Users/blitzen12/Workspace/laravel-chat-app/vendor/inertiajs/inertia-laravel/src/Middleware.php(82): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Inertia\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#36 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#43 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#44 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#45 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#46 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#47 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /Users/blitzen12/Workspace/laravel-chat-app/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#64 /Users/blitzen12/Workspace/laravel-chat-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#65 /Users/blitzen12/Workspace/laravel-chat-app/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#66 /Users/blitzen12/Workspace/laravel-chat-app/server.php(21): require_once('/Users/blitzen12/W...')
#67 {main}
"} `

It would be great if someone can help me pinpoint the steps to get it work.

Thank you.

**Comment by elbojoloco** [comment]
What are your PUSHER_ environment variables in your laravel app?

**Comment by elbojoloco** [comment]
If those are set correctly (in line with your soketi app settings), you should also make sure to overwrite the pusher host in your Laravel config: `config/broadcasting.php`:

```
        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'host' => env('PUSHER_APP_HOST', '127.0.0.1'), // Add this key
                'useTLS' => false, // Depending on if your soketi is running on https or not
            ],
        ],
```
