### ISSUE TITLE
How to use config file with docker?

### ISSUE THREAD

**Issue by zabavnikov** [soketi/soketi#354]

**Comment by Purtl** [comment]
I have the same problem. 
Can't really read out of the documentation how to do that.
Probably it's something of 'common-docker-knowledge', but... I apparently lack that. Could someone help us out there?

**Comment by Gessto** [comment]
Hi, i think that is not possible. Becouse that params are hardcoded in server.js file.
<img width="1439" alt="Screenshot 2022-03-02 at 04 18 16" src="https://user-images.githubusercontent.com/15093782/156288499-e55be12a-a9b6-4d6d-a96b-0f3a896385e1.png">

<img width="1268" alt="Screenshot 2022-03-02 at 04 17 47" src="https://user-images.githubusercontent.com/15093782/156288453-6d4e57e5-24f4-44ee-ba58-1eb7a50fb3bb.png">
.
