### ISSUE TITLE
New app and frontend UI

### ISSUE THREAD

**Issue by asad-awadia** [soketi/soketi#355]
Hey @rennokki great work here really love this

I had two questions

1. How do I create a new app? do I have to insert the row into the DB directly? or is there an API to create it?

2. Is there no web UI for this?

**Comment by ditschedev** [comment]
1. Yes, you have to manually configure them in your active driver or create an own adapting api that inserts them into the database. There is currently no api to my knowledge.
2. No, there is currently no management UI available. The repository focuses on the websocket server itself.

**Comment by asad-awadia** [comment]
ok got it - thanks!
