### ISSUE TITLE
How to publish a message? 

### ISSUE THREAD

**Issue by santiblanko** [soketi/soketi#363]
I don't see how to publish in the documentation and the pusher trigger give me error.  Can you help me? :D 

`const PusherJS = require('pusher-js');

let client = new PusherJS('app-key', {
    wsHost: '127.0.0.1',
    wsPort: 6001,
    forceTLS: false,
    encrypted: true,
    disableStats: true,
    enabledTransports: ['ws', 'wss'],
});

client.subscribe('chat-room').bind('message', (message) => {
    alert(`${message.sender} says: ${message.content}`);
});

client.trigger('chat-room', 'message', {

  "message": "hello world"

});`

**Comment by rennokki** [comment]
To broadcast messages, you shall use the [`pusher-http-node` package](https://github.com/pusher/pusher-http-node)

**Comment by drpshtiwan** [comment]
The trigger will not fire any event to Laravel echo with the Node or pusher PHP package. This is my configuration.
```javascript
const Pusher = require("pusher")

const pusher = new Pusher({
    appId: "app-id",
    key: "app-key",
    secret: "app-secret",
    useTLS: false, 
    host: "127.0.0.1",
    port: 6001, 
  });

pusher.trigger('websocket','WebsocketEvent',{message:'FROM NODE'})
```

This is Laravel echo configuration:
```javascript
import Echo from 'laravel-echo';

import Pusher from 'pusher-js';
window.Pusher = Pusher;

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: import.meta.env.VITE_PUSHER_APP_KEY, //app-key
    wsHost: import.meta.env.VITE_PUSHER_HOST, // 127.0.0.1
    wsPort: import.meta.env.VITE_PUSHER_PORT , // 6001
    wssPort: import.meta.env.VITE_PUSHER_PORT, // 6001
    forceTLS: false ,
    disableStats: true,
    enabledTransports: ['ws', 'wss'],
});
```

Is there any way to trigger to Laravel Echo?
