### ISSUE TITLE
Consider migrating to @colors/colors

### ISSUE THREAD

**Issue by leio** [soketi/soketi#375]
I did not investigate very deeply yet on if it's really the way forward at this point, but it looks like changing from `colors` to `@colors/colors` should be considered in the package list: https://github.com/Marak/colors.js/issues/340

**Comment by andriycraft** [comment]
@DABH Stop advertising your package.

**Comment by DABH** [comment]
@andriycraft Please investigate the history of the issue and the history of the colors repository before making non-constructive comments like this.  @colors/colors belongs to the community.  If you feel there is anything missing from the package, feel free to open an issue or pull request and the community will do our best to help.
