### ISSUE TITLE
Publish message with Golang Pusher SDK

### ISSUE THREAD

**Issue by billypap1** [soketi/soketi#379]
Hello, first of all congratulations for this amazing library. 
I have integrated successfully the soketi server in a droplet at Digital Ocean for testing. The server works great and I can connect to it via Pusher SDK Client.  
For backend I use Pusher's Golang SDK, I can authorize the user but I can't publish messages (Trigger). 

```
pusherClientSetup := pusher.Client{
		AppID:      "AppID",
		Key:        "Key",
		Secret:     "Secret",
		Host:       "SoketiHost",
		Secure:     true,
	}

	data := map[string]string{"message": "message"}
	pusherClientSetup.Trigger(channel, "newMessage", data)
```

Any idea?

**Comment by billypap1** [comment]
Skip the above issue, my mistake. In Host it doesn't need to add "http".
How much RAM-CPU do I need in order to have connected 1000-2000 concurrent users using Soketi?

**Comment by rennokki** [comment]
@billypap1 It depends on the connection/disconnection rate and the current network traffic. Usually, the network is the throttle before the resources are becoming an issue.

Make sure to have qualitative network in place (more Gbps as possible to handle the traffic). Usually this can be done with less < 4 CPU / 4 GB RAM.

**Comment by PostworkGR** [comment]
@rennokki So if I deploy soketi in a droplet with 4 CPU - 4GB RAM, it would cost me ~ 48$ (exc VAT). That's 50% cheaper than Pusher if we suppose that there are 2000 connected users concurrently. I would say it would support more than 2000 concurrent connections if they are idle. Am I right? 

For example, a basic droplet 1 GB Ram - 1 CPU how many users would support using soketi?

**Comment by billypap1** [comment]
@rennokki So if i deploy soketi in a 4gb-4CPU droplet it would cost me 48$ (exc Vat).  That's 50% cheaper than using Pusher with 2000 concurrent users. If we skip the connection/disconnection rate etc, what would be the ratio for RAM-CPU? Can I for example, deploy it in 2GB RAM-2CPU droplet for 2000 concurrent connections (half of them idle) or it would crash?
