### ISSUE TITLE
[Kubernetes/Charts] Cluster adapter CNI usage

### ISSUE THREAD

**Issue by fibis** [soketi/soketi#409]
We are using soketi in our laravel application in a kubernetes cluster with multiple instances synced via the cluster mode. We are also using presence channels from laravel echo.

In our setup, we have three instances and one presence channel with 2 participants. In our test, the messages arrived with a probability of 1/3. If we scaled the instances down to one, our tests always worked smoothly.

Is it possible that presence channels are not synchronized correctly across all instances?

**Comment by rennokki** [comment]
Kubernetes works with the Cluster mode only if your CNI supports broadcasting, multicasting or unicasting: https://github.com/soketi/charts/issues/13 and is also described here: https://docs.soketi.app/advanced-usage/horizontal-scaling/clustering

Weave should work fine with soketi 😁

**Comment by fibis** [comment]
Funny, I have seen the changes to the helm chart today and thought, that this could be relevant. Since we are using GKE with the default CNI, is there a way to test easily, if broadcasting, multicasting or unicasting is supported?

**Comment by rennokki** [comment]
Currently not, but can be made a demo with Discovery to get deployed on cluster: https://github.com/wankdanker/node-discover

Perhaps a chart demo might be useful. 😁

**Comment by rennokki** [comment]
See: https://github.com/soketi/charts/issues/10
