### ISSUE TITLE
Soketi with Laravel in different domains

### ISSUE THREAD

**Issue by felipesmendes** [soketi/soketi#418]
Soketi with Laravel
Hello Guys,

I'm trying to use real-time notifications using Soketi 

So I createg the Soketi server in one separeted server with nodejs on port 6001 and SSL using letsencrypt.

Then I Created the notification

Added the JS script to layout:
```
 Echo.private('App.User.' + {{Auth::id()}})
        .notification((data) => {
         console.log(data);
        });
```

Added the this code compiled in layout too:

```
import Echo from 'laravel-echo';
window.Pusher = require('pusher-js');
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    wsHost: process.env.MIX_PUSHER_HOST,
    wsPort: process.env.MIX_PUSHER_PORT,
    wssPort: process.env.MIX_PUSHER_PORT,
    forceTLS: false,
    encrypted: true,
    disableStats: true,
    enabledTransports: ['ws', 'wss'],
});
```
So when I was in development ambient the notifications cakes properly, sended by one server without SSL (http://sede.inoprime.com.br), but when I was on production server It not work and this server has SSL and its diferent from Soketi server.
Application Laravel (https://trackerprime.inoprime.com.br)
Soketi Server (https://servicos.inoprime.com.br)

I found this two diferences when the aplications calls the websocket link: wss://servicos.inoprime.com.br:6001/app/app-key?protocol=7&client=js&version=7.0.6&flash=false 

In development the response is:

```
{event: "pusher_internal:subscription_succeeded", channel: "private-App.User.1"}
```
In Production I got:

{
    "event": "pusher:connection_established",
    "data": "{\"socket_id\":\"8565042074.5045547206\",\"activity_timeout\":30}"
}
Anyone have any idea what they might be getting?

**Comment by alexhackney** [comment]
Seems like it could be a config issue. Are you sure the App Key is correct?

The server is responding to requests but not to wss requests.

**Comment by alexhackney** [comment]
You have to create a config.

https://docs.soketi.app/getting-started/environment-variables

**Comment by felipesmendes** [comment]
I already using this chrome extension See the connection working:
![image](https://user-images.githubusercontent.com/992965/158852200-952349c0-2f0a-451d-a63c-eef0687d5ed4.png)

The .env is same in both of servers (develop and production) 

The unique thing that is diferent is the origin of requisition:

### Development:
```
Accept-Encoding: gzip, deflate, br
Accept-Language: pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control: no-cache
Connection: Upgrade
Host: socket.inoprime.com.br:6002
Origin: http://localhost:8000
Pragma: no-cache
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Key: 2qKJFymINL4suwoMXf7ieA==
Sec-WebSocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
```
![image](https://user-images.githubusercontent.com/992965/158852718-7c3d3515-fe99-418a-ac1a-a0ccbaf0f921.png)



### Production:
```
Accept-Encoding: gzip, deflate, br
Accept-Language: pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control: no-cache
Connection: Upgrade
Host: socket.inoprime.com.br:6002
Origin: https://trackerprime.inoprime.com.br
Pragma: no-cache
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Key: KeO/uAPqgRC0SCWdoX7Mkw==
Sec-WebSocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
```
![image](https://user-images.githubusercontent.com/992965/158852768-c271dc1d-c0e8-4be4-abe9-5c292afcba5c.png)

**Comment by alexhackney** [comment]
It's clearly not the same server.

You said you were connecting to:
`Soketi Server (https://servicos.inoprime.com.br/)`
in your original post

but here you're connecting to 
socket.inoprime.com.br:6002

Different server, different port.

I can connect to the second server with the tool from here so it's not a server issue. It's a config issue.

Make sure your prod env has
MIX_PUSHER_APP_KEY,
MIX_PUSHER_HOST,
MIX_PUSHER_PORT,
MIX_PUSHER_PORT,

And they are set properly.

**Comment by alexhackney** [comment]
Also, locally you're not using an SSL and in production you are.

Your server is probably setup for only wss.

So you could try removing the ws entries and force tls.

Your screenshots dont really help, I'd need to see the wss server its trying to connect to on both envs to verify.

**Comment by felipesmendes** [comment]
@alexhackney Yes its beause I changed to this configuration thinking thats the problem in port or ssl

https://docs.soketi.app/getting-started/backend-configuration/nginx-configuration

and the prod end has this configuration like the official documentation 

```
MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_HOST="${PUSHER_HOST}"
MIX_PUSHER_PORT="${PUSHER_PORT}"
```

**Comment by felipesmendes** [comment]
> Also, locally you're not using an SSL and in production you are.
> 
> Your server is probably setup for only wss.
> 
> So you could try removing the ws entries and force tls.
> 
> Your screenshots dont really help, I'd need to see the wss server its trying to connect to on both envs to verify.

For sure, but where in the configuration of the server I setup for ws and wss?

**Comment by alexhackney** [comment]
Your server is functioning.

This would be in echo config.

**Comment by felipesmendes** [comment]
> But are the values the same?
> 
> All MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}" does is make MIX_PUSHER_APP_KEY = PUSHER_APP_KEY and makes it available in mix.
> 
> Is PUSHER_APP_KEY the same in both envs? along with the other env vars?

Yes, in both of it are the same.

**Comment by felipesmendes** [comment]
> Your server is functioning.
> 
> This would be in echo config.

The Echo config is this:

```
window.Echo = new laravel_echo__WEBPACK_IMPORTED_MODULE_0__["default"]({
  broadcaster: 'pusher',
  key: "tracker",
  wsHost: "socket.inoprime.com.br",
  wsPort: "6002",
  wssPort: "6002",
  forceTLS: false,
  encrypted: true,
  disableStats: true,
  enableLogging:true,
  enabledTransports: ['ws', 'wss']
});
```

**Comment by alexhackney** [comment]
Right so remove ws and set forcetls to true

**Comment by felipesmendes** [comment]
> Right so remove ws and set forcetls to true

I changed to this configuration:
```
window.Echo = new laravel_echo__WEBPACK_IMPORTED_MODULE_0__["default"]({
  broadcaster: 'pusher',
  key: "tracker",
  wsHost: "socket.inoprime.com.br",
  wsPort: "6002",
  wssPort: "6002",
  forceTLS: true,
  encrypted: true,
  disableStats: true,
  enableLogging:true,
  enabledTransports: ['wss']
});
```

and then the application did connected to soketi server:
![image](https://user-images.githubusercontent.com/992965/158862969-2a5ccac3-4221-44f4-b83f-a29ccca68e8b.png)

**Comment by alexhackney** [comment]
So youre good?

**Comment by felipesmendes** [comment]
Sorry, I spelled it wrong, the application did not connect to the Soketi
server.

**Comment by elbojoloco** [comment]
Try changing `enabledTransports: ['wss']` to `enabledTransports: ['ws', 'wss']`

**Comment by felipesmendes** [comment]
> Try changing `enabledTransports: ['wss']` to `enabledTransports: ['ws', 'wss']`

Hello @elbojoloco, before the enabledTransports it was like you told, with ws and wss configuration then in developmento the Laravel Echo subscribed to private channel as espected. (See the image)
![image](https://user-images.githubusercontent.com/992965/158993314-2e57b8ee-fe35-47be-9085-7ca9f4071156.png)

But in production the Laravel Echo client just connect to Soketi server and don't subscribe to a private channel as developement server did. Check the image.
![image](https://user-images.githubusercontent.com/992965/158993442-5a43ad48-48bb-4555-9ff4-f706c0923f43.png)

**Comment by elbojoloco** [comment]
It's a private channel, and your screenshot does not include XHR, so I can't see if your channel auth call is successful, but that would be my first bet of where your problem lies.

**Comment by felipesmendes** [comment]
Sorry @elbojoloco, here is the XHR request of auth working properly

![image](https://user-images.githubusercontent.com/992965/159358765-c3c33c91-d92d-47d3-a39d-ddb7d1cb0c49.png)
![image](https://user-images.githubusercontent.com/992965/159358802-56c5a8d4-4abc-4534-a30f-5fefd374bde1.png)
