### ISSUE TITLE
Note

### ISSUE THREAD

**Issue by reposys** [soketi/soketi#420]
Reading the README.md file, the first lines say that Russia invaded Ukraine, breaking all laws, including the UN charter. But, who are you? Are you a diplomat? Politician? Well, at least you are a journalist to speak like that? Have you visited this area? Do you know everything that is happening there and has been happening for eight years (since 2014)? Well, of course not. Why do you need this... Never get involved in politics! You have no idea what is happening on the territory of Ukraine! If you have specific arguments about the events in Ukraine, then express them on the appropriate platforms. And this platform for the source code! Please be in solidarity with all participants in this project. Thanks!

**Comment by jstark518** [comment]
@reposys stfu

**Comment by rennokki** [comment]
I have locked this as I don't want to reply in terms of politics, but in the terms of being a human. Please check #StandWithUkraine here: https://github.com/vshymanskyy/StandWithUkraine

This movement is not about restricting Russian people that I'm sure they are kind to their core and they are wrongly represented by their president, in the awe of war. It's about cutting all the Russian finacing, one way or another, so it will eventually be unable to sustain the war.

I cannot go there and fight for Ukrainians, unfortunately. But sanctions came and will continue to come. The action we took is a personal choice, that is not meant to be hateful towards Russians, but it comes as a consequence of their internal ruling.

One day, these will be lifted.

🇺🇦 Слава Україні!
