### ISSUE TITLE
[bug] Horizontal scaling do not work as expected with Redis driver

### ISSUE THREAD

**Issue by L3o-pold** [soketi/soketi#428]
With 3 Soketi node and the redis adapter (tested with redis and redis cluster), some message not being delivered to client.

**Comment by rennokki** [comment]
The master messages are from the discovery module, that is completely independent of Redis, unless you use the Private Network/Cluster mode instead of Redis, but there are special criteria when you can use it.

**Comment by L3o-pold** [comment]
Is it an expected behavior to randomly (client) not getting message with vertical scaling and redis then?

**Comment by L3o-pold** [comment]
I do not reproduce the bahavior.

**Comment by L3o-pold** [comment]
The behavior came again without any server change.

**Comment by rennokki** [comment]
@L3o-pold I couldn't dedicate more time on investigating bugs.

It seems that the bug should be completely eradicated in the upcoming version (2.x). I wasn't able to reproduce it. For what I know, the Redis client is able to auto-resubscribe to the existing channels.

Also, the upcoming version is using better channel names for PubSub, so it should be improved on sharding with Redis 7.0 in Cluster Mode, and mitigate this issue.

I will keep this open and wait in case this occurs in the future.

**Comment by L3o-pold** [comment]
It seems to be fixed in 2.x as I can't reproduce anymore too.

**Comment by rennokki** [comment]
I will keep this issue up for reference. I will try to reproduce it in a controlled environment in the near future.

Can you share some of the versions you were using before? (Redis & Soketi)

**Comment by L3o-pold** [comment]
@rennokki should be [0.33.1](https://github.com/soketi/soketi/releases/tag/0.33.1) and redis 6 if I remember correctly.
