### ISSUE TITLE
App key does not exist while using .env file

### ISSUE THREAD

**Issue by erickneverson** [soketi/soketi#429]
Laravel 8
Php 7.4
Ubuntu 20
Node v16.14.2

**Error**

```
{
   "event":"pusher:error",
   "data":{
      "code":4001,
      "message":"App key x9w3uyytpetqdwtq does not exist."
   }
}
```

If I hardcode the default app key in the bootstrap settings for Echo (to test), it finds the app but the problem then is with authorization:

```
{
   "event":"pusher:subscription_error",
   "channel":"private-company.3603",
   "data":{
      "type":"AuthError",
      "error":"The connection is unauthorized.",
      "status":401
   }
}
```

**.env**

```
PUSHER_APP_ID=1234567
PUSHER_APP_KEY=x9w3uyytpetqdwtq
PUSHER_APP_SECRET=r9uyqyyycupbuqga

PUSHER_HOST=127.0.0.1
PUSHER_PORT=6001
MIX_PUSHER_HOST="${PUSHER_HOST}"
MIX_PUSHER_PORT="${PUSHER_PORT}"
DB_REDIS_HOST="${REDIS_HOST}"
DB_REDIS_PORT="${REDIS_PORT}"
DB_REDIS_PASSWORD="${REDIS_PASSWORD}"
SOKETI_DEBUG=1
DEFAULT_APP_ID="${PUSHER_APP_ID}"
DEFAULT_APP_KEY="${PUSHER_APP_KEY}"
DEFAULT_APP_SECRET="${PUSHER_APP_SECRET}"
```

**broadcasting.php**

```
'connections' => [

        'pusher' => [
            'driver'  => 'pusher',
            'key'     => env('PUSHER_APP_KEY', 'app-key'),
            'secret'  => env('PUSHER_APP_SECRET', 'app-secret'),
            'app_id'  => env('PUSHER_APP_ID', 'app-id'),
            'options' => [
                //'cluster' => env('PUSHER_APP_CLUSTER'),
                'host'      => env('PUSHER_HOST', '127.0.0.1'),
                'port'      => env('PUSHER_PORT', 6001),
                'scheme'    => env('PUSHER_SCHEME', 'http'),
                'encrypted' => false, // TODO
                'useTLS'    => 'https' === env('PUSHER_SCHEME'), // TODO
            ],
        ],
```
**bootstrap.js**

```
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    //cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    forceTLS: false,
    disableStats: true,
    wsHost: window.location.hostname,
    wsPort: 6001,
    wssPort: 6001,
    enabledTransports: ['ws', 'wss'],
    authorizer: (channel, options) => {
        return {
            authorize: (socketId, callback) => {
                axios.post('/broadcasting/auth', {
                    socket_id: socketId,
...
```
**welcome.blade.php**

```
...
<script src="{{ asset('js/app.js') }}"></script>
    <script>
        Echo.private('company.3603')
        .listen('.import-progress-updated', (e) => {
            console.log(e.percentComplete);
        });
    </script>
```

**Comment by kondohiroki** [comment]
Can you try this instead? 
`<script src="{{ mix('/js/app.js') }}"></script>`
in your `welcome.blade.php` file

**Comment by erickneverson** [comment]
@kondohiroki same result unfortunately.

**Comment by kondohiroki** [comment]
Hmmm, How did you run the soketi service? with docker?
Something like this
```
  soketi:
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    environment:
        DEBUG: 1
        METRICS_SERVER_PORT: 9601
        ADAPTER_DRIVER: local
        DEFAULT_APP_ID: 1234567
        DEFAULT_APP_KEY: x9w3uyytpetqdwtq
        DEFAULT_APP_SECRET: r9uyqyyycupbuqga
    ports:
        - '${SOKETI_PORT:-6001}:6001'
        - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
    restart: always
```

**Comment by erickneverson** [comment]
> Hmmm, How did you run the soketi service? with docker? Something like this
> 
> ```
>   soketi:
>     image: 'quay.io/soketi/soketi:latest-16-alpine'
>     environment:
>         DEBUG: 1
>         METRICS_SERVER_PORT: 9601
>         ADAPTER_DRIVER: local
>         DEFAULT_APP_ID: 1234567
>         DEFAULT_APP_KEY: x9w3uyytpetqdwtq
>         DEFAULT_APP_SECRET: r9uyqyyycupbuqga
>     ports:
>         - '${SOKETI_PORT:-6001}:6001'
>         - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
>     restart: always
> ```

Not quite.  I basically install it within my DockerFile

**yaml file**
```
build:
      context: .
      dockerfile: ./docker/Dockerfile
```

**DockerFile**

```
RUN npm install -g @soketi/soketi
```
and user **Supervisor** to keep the service running

```
[program:soketi]
process_name=%(program_name)s
command=soketi start
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
# TODO user=ubuntu
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/soketi-supervisor.log
stopwaitsecs=59
stopsignal=sigint
```

**Comment by kondohiroki** [comment]
Oh! I think you can use configuration file like this [File configuration](https://docs.soketi.app/getting-started/environment-variables#file-configuration)

and you can add option to your supervisor command to map the config file
```
[program:soketi]
process_name=%(program_name)s
command=soketi start --config=/path/to/config.json
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
# TODO user=ubuntu
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/soketi-supervisor.log
stopwaitsecs=59
stopsignal=sigint
```

**Comment by erickneverson** [comment]
> Oh! I think you can use configuration file like this [File configuration](https://docs.soketi.app/getting-started/environment-variables#file-configuration)
> 
> and you can add option to your supervisor command to map the config file
> 
> ```
> [program:soketi]
> process_name=%(program_name)s
> command=soketi start --config=/path/to/config.json
> autostart=true
> autorestart=true
> stopasgroup=true
> killasgroup=true
> user=root
> # TODO user=ubuntu
> numprocs=1
> redirect_stderr=true
> stdout_logfile=/var/www/storage/logs/soketi-supervisor.log
> stopwaitsecs=59
> stopsignal=sigint
> ```

Even while doing that, I still needed to explicitly set the credentials my .env file to get past the error:

**from this**
```
DEFAULT_APP_ID="${PUSHER_APP_ID}"
DEFAULT_APP_KEY="${PUSHER_APP_KEY}"
DEFAULT_APP_SECRET="${PUSHER_APP_SECRET}"
```

**to this**
```
DEFAULT_APP_ID=1234567
DEFAULT_APP_KEY=x9w3uyytpetqdwtq
DEFAULT_APP_SECRET=r9uyqyyycupbuqga
```

I'm wondering if I need the json file at all at this point.  Nevertheless, the next head scratcher is that my authorization api is successful but I receive the following from the websocket server for the pusher:subscribe event:

API: http://localhost:8787/broadcasting/auth

```
{
   "event":"pusher:subscription_error",
   "channel":"private-company.3603",
   "data":{
      "type":"AuthError",
      "error":"The connection is unauthorized.",
      "status":401
   }
}
```
I can confirm that my channel setup is actually returning true
```
Broadcast::channel('company.{id}', function ($user, $id) {
    Log::debug('Broadcast::channel user',[$id, $user->getCompanyId() === (int) $id]);
    return $user->getCompanyId() === (int) $id;
});
```

Any tips?  Thanks for the support thus far.

**Comment by kondohiroki** [comment]
@erickneverson 
My pleasure, Maybe I'm missing something
for the `.env` file you can run `php artisan optimize` to re-caching everything
and for the authorization problem could you show me a network debugging?

<img width="639" alt="Screen Shot 2565-04-01 at 09 46 21" src="https://user-images.githubusercontent.com/49369000/161185961-7a212b57-811e-451c-8c2b-fd861830c8a7.png">

<img width="544" alt="Screen Shot 2565-04-01 at 09 46 35" src="https://user-images.githubusercontent.com/49369000/161185976-c13ca756-46bf-430b-a71a-0a531ff761c0.png">

**Comment by erickneverson** [comment]
optimized helped, thanks.  Typically, I don't cache for local dev so I'll have to remember that.  Here's. my network debug:

<img width="863" alt="auth_request" src="https://user-images.githubusercontent.com/22592642/161281908-47bcb434-701a-4fd7-9a8f-2e5a99a1f145.png">

<img width="1420" alt="payload" src="https://user-images.githubusercontent.com/22592642/161282026-c2c1592e-4c06-44bd-84ae-1ed71e17d0f2.png">

<img width="1480" alt="pusher_subscribe" src="https://user-images.githubusercontent.com/22592642/161282056-aef960f4-218d-45aa-818f-15ed72d740c6.png">

**Comment by kondohiroki** [comment]
That's great! 😄  you did well @erickneverson 
I have a question, Did you use api authentication likes laravel-passport or santum?

If answer is Yes then you need to add your token to a websocket header
like this
```
  window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    wsHost: process.env.MIX_PUSHER_HOST,
    wsPort: process.env.MIX_PUSHER_PORT,
    wssPort: process.env.MIX_PUSHER_PORT,
    forceTLS: process.env.MIX_PUSHER_SCHEME === 'https',
    encrypted: true,
    disableStats: true,
    enabledTransports: ['ws', 'wss'],
    auth: {
      headers: {
        Authorization: `Bearer <YOUR TOKEN>`,
      },
    },
  })
```

and add this code `Broadcast::routes(['middleware' => ['auth:api']]);` to your `BroadcastServiceProvider.php`
![Screen Shot 2565-04-01 at 22 52 50](https://user-images.githubusercontent.com/49369000/161299200-4497e725-567c-427c-9b0c-c65d89ec1316.png)

If answer is No
I still have no idea what's happening, but can you test a simple thing for me
1.  Make your channel return true
```
Broadcast::channel('company.{id}', function ($user, $id) {
    Log::debug('Broadcast::channel user',[$id, $user->getCompanyId() === (int) $id]);
    return true;
});
```
2.  Make sure you're using public-channel not a private-channel in your Event file
```
    public function broadcastOn()
    {
        return new Channel("company.{id});
    }
```
3. Test

Please let me know the result 🚀 🚀 🚀

**Comment by erickneverson** [comment]
Thanks @kondohiroki 

I use my own authentication middleware which utilizes our own access_token. Public channel has always worked for me.  The issue is when I switch to private channels. 

For what it's worth, I tried forcing the channel to return true but the issue remains.

**bootstrap.js**
```
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    //cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    forceTLS: false,
    disableStats: true,
    wsHost: window.location.hostname,
    wsPort: 6001,
    wssPort: 6001,
    enabledTransports: ['ws', 'wss'],
    authorizer: (channel, options) => {
        return {
            authorize: (socketId, callback) => {
                axios.post('/broadcasting/auth', {
                    socket_id: socketId,
                    channel_name: 'company.3603',
                    access_token: "censored"
                })
...
```

**Comment by kondohiroki** [comment]
I believe you need to add your token to websocket header
I hope it's work! 🙏

**Comment by erickneverson** [comment]
@kondohiroki 

Success!  Instead of customizing the auth request, I just needed to use my access_token in the manner you suggested:

```
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    //cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    forceTLS: false,
    disableStats: true,
    wsHost: window.location.hostname,
    wsPort: 6001,
    wssPort: 6001,
    enabledTransports: ['ws', 'wss'],
    auth: {
        headers: {
          Authorization: 'Bearer <YOUR TOKEN>',
        },
      }
});
```

Thanks again for your support!
