### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by StrangerGithuber** [soketi/soketi#439]
Hello
I am using laravel as backend to everything and frontend is a desktop application which created with ElectronJS.

On the frontend is like this:
```
import Echo from 'laravel-echo';

window.Pusher = require('pusher-js');

window.Echo = new Echo({
  broadcaster: 'pusher',
  key: 'keysomething',
  authEndpoint: 'http://127.0.0.1/broadcasting/auth',
  host: '127.0.0.1:6001',
  wsHost: '127.0.0.1',
  wsPort: 6001,
  wssPort: 6001,
  forceTLS: false,
  encrypted: true,
  disableStats: true,
  enabledTransports: ['ws', 'wss'],
  auth:
  {
    headers:
    {
      'Authorization': 'Bearer ' + 'frfweewfwefwefwfwefwefwe'
    }
  }
});

window.Echo.private('testsocketthing').listen('LetsTestIt', (payload) => {
            console.log(payload);
        });
```

Backend soketi config:
```
{
    "appManager.array.apps.0.id": "aaaa",
    "appManager.array.apps.0.key": "keysomething",
    "appManager.array.apps.0.secret": "wfewweewwe",
    "debug": true,
    "port": 6001,
    "cors": {
        "origin": ["localhost:8080", "http://localhost:8080"]
    }
}
```

But I get this error even so:
```
Access to XMLHttpRequest at 'http://127.0.0.1/broadcasting/auth' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

What I am doing wrong?

**Comment by jstark518** [comment]
One config has 127.0.0.1 and one has localhost, I would try making them match.

**Comment by StrangerGithuber** [comment]
It doesn't help. If the backend in different place than the desktop application then it will not match eventually. Therefore I need to allow somehow the localhost:8080.
The desktop application will running on the localhost:8080 however the production backend part would work on the namecheap.com webhosting.

**Comment by StrangerGithuber** [comment]
Alright. I found somewhere else the answer.
If someone is using pusher as broadcaster then you can use this method to allow other applications to use the server.

Open the app/Providers/BroadcastServiceProvider.php file. In the boot function you need to change the `Broadcast::routers()` part to  `Broadcast::routes(['prefix' => 'api', 'middleware' => ['auth:api']]);` .

Open the config/cors.php file and add to the paths this part `'broadcasting/auth'`. Restart soketi and it will work. On the frontend the authentication needs to be there otherwise you get the same error as me.

*I am using the "you" because if someone is reading this and using this method then this method for them.*
