### ISSUE TITLE
[bug] member_removed webhook not working after v0.32.2

### ISSUE THREAD

**Issue by liverocaisson** [soketi/soketi#502]
When the client socket is disconnected, the webhook on member_removed event worked perfectly.
But since > v0.32.2+, it's not working anymore.

{
    "headers": {
        "Authorization": "Bearer xxxxx"
    },
    "url": "http://xxxxx",
    "filter": {
        "channel_name_starts_with": "xxxxx"
    },
    "event_types": ["member_removed"]
}

**Comment by rennokki** [comment]
Can you share the configuration of your app? 🤔

**Comment by rennokki** [comment]
I did not seem to be able to replicate this. 🤔 If you use Redis for the queue system, you might not get old jobs back as the payload is handled other way.

**Comment by liverocaisson** [comment]
@rennokki Hello, I'm not using Redis.

And it still not working on soketi version 1.0.0.

I have attached a full project sample in Laravel, so you can replicate the bug.

[example-app.zip](https://github.com/soketi/soketi/files/8705292/example-app.zip)

You can find the config file inside the zip 

`soketi start --config=/<path>/soketi.config.json`

### Version 0.32.2 (Logs)

![Capture_d’écran_2022-05-17_à_13_39_47](https://user-images.githubusercontent.com/79827883/168732861-483a0c87-b901-476b-9e72-7d887cd2f9ed.jpg)

Laravel debug log :

![Capture d’écran 2022-05-17 à 13 40 09](https://user-images.githubusercontent.com/79827883/168732899-6f1d1241-436b-4566-b033-fa24d9e91395.png)

The hook "member_added" is called properly after the socket connection.
And the hook "member_removed" is called properly after the socket disconnection.

### Version 1.0.0 (Logs)

![Capture_d’écran_2022-05-17_à_13_51_24](https://user-images.githubusercontent.com/79827883/168733118-0344c9ed-8a81-4796-b7ff-be436f4e85de.jpg)

![Capture d’écran 2022-05-17 à 13 52 19](https://user-images.githubusercontent.com/79827883/168733244-c65055c9-46c9-4c90-a393-858ffd3a457f.png)

Laravel debug log :

![Capture d’écran 2022-05-17 à 13 52 43](https://user-images.githubusercontent.com/79827883/168733277-d9e3cfe3-426d-48d9-a138-3aafe5b16d9c.png)

The hook "member_added" is called properly after the socket connection. But not on disconnection.

**Comment by rennokki** [comment]
Managed to find the issue. It's only in the case you have multiple webhooks declared.

**Comment by rennokki** [comment]
It got fixed in `0.34.1` and will release a patch version for 1.x too.
