### ISSUE TITLE
Authorized connections

### ISSUE THREAD

**Issue by billypap1** [soketi/soketi#525]
Hello, first of all congratulations for this library. It works great! 
In pusher I can allow only authorized clients to connect in the server ->[https://pusher.com/docs/channels/using_channels/authorized-connections/](url) . 
Is this possible with Soketi? If yes, how can i enable it? (I don't want anyone to connect to websockets server, only the authorized)

**Comment by hirbod** [comment]
Would love to see this supported as well. I just finished implementing it into my React-Native app. At least private channel auth is already possible and working.

**Comment by billypap1** [comment]
@rennokki I think this is a critical feature. Without it, anyone can connect to ws server without any security check.  An other useful feature would be to allow only authorized users to publish messages from client.

**Comment by hirbod** [comment]
Is there already documentation for this added?

**Comment by rennokki** [comment]
https://docs.soketi.app

**Comment by billypap1** [comment]
@rennokki thank you very much for the quick implementation of the feature. Great work!!
