### ISSUE TITLE
SSL not working anymore after upgrading to V1

### ISSUE THREAD

**Issue by francoism90** [soketi/soketi#528]
```
$ cat /etc/supervisor.d/soketi.ini
[program:soketi]
process_name=%(program_name)s_%(process_num)02d
command=soketi start --config=/etc/soketi/config.json
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=http
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/soketi-supervisor.log
stopwaitsecs=60
stopsignal=sigint
minfds=10240
environment=HOME="/etc/soketi"
```

```
$ cat /etc/soketi/.env
SOKETI_SSL_CERT='/etc/nginx/ssl/cert.pem'
SOKETI_SSL_KEY='/etc/nginx/ssl/key.pem'
SOKETI_DEBUG=1
```

```
🎉 Server is up and running!   
   📡 The Websockets server is available at 127.0.0.1:6001   
   🔗 The HTTP API server is available at http://127.0.0.1:6001   
   🎊 The /usage endpoint is available on port 9601.
```
It should state https://127.0.0.1:6001, but it's listing over HTTP instead.

Also there's a typo on https://docs.soketi.app/getting-started/ssl-configuration

```SOKETI_ISSL_CERT => SOKETI_SSL_CERT```

**Comment by francoism90** [comment]
Downgrading to `0.33.3` fixes the issue.. maybe something goes wrong with the new enviroment parsing?

**Comment by rennokki** [comment]
@francoism90 Sorry for the late response, I'm trying to do it as fast as possible. 😬 

What does your json config contain? Also, use `SOKETI_DEBUG` and see how the configuration looks like for `ssl`

**Comment by francoism90** [comment]
@rennokki Thanks for looking into the issue. :)

This is my `config.json`:
```
{
    "debug": true,
    "port": 6001,
    "appManager.array.apps": [
        {
            "id": "app-id",
            "key": "app-key",
            "secret": "app-secret"
        }
    ],
    "ssl": {
	"certPath": "/etc/nginx/ssl/cert.pem",
	"keyPath": "/etc/nginx/ssl/key.pem"
    }
}
```
Changing port to `6002` works, but the SSL configuration doesn't seem to be picked up.

Do you actually recommend to use SSL directly, or should one use a (Nginx/Apache) proxy instead?

Thanks!

**Comment by rennokki** [comment]
Weird, it seems with the following configuration the SSL is being picked up:

```
SOKETI_SSL_CERT=tests/ssl/cert.pem
SOKETI_SSL_KEY=tests/ssl/key.pem
```

I think there is something weird up your certificate. I'm seeing that the SSL files are being generated by NGINX (I think). It's best to create a proxy via NGINX: https://docs.soketi.app/getting-started/backend-configuration/nginx-configuration

**Comment by francoism90** [comment]
@rennokki I'm using [mkcert](https://github.com/FiloSottile/mkcert), the cert is only used locally.

I'll try to use a nginx proxy, thanks. :)
