### ISSUE TITLE
How many is the max concurrent connections that soketi can handle per instance?

### ISSUE THREAD

**Issue by lechatthecat** [soketi/soketi#556]
I think I will use soketi for our website. But my website has massive traffic, so I want to know how many is the max concurrent connections that soketi can handle per instance?
If I use horizontal scaling, the max concurrent number will be also increased?

Do I need to do something like this?
https://stackoverflow.com/a/58949475/6180050

**Comment by lechatthecat** [comment]
Do I need to do something like this?
https://stackoverflow.com/a/58949475/6180050

**Comment by rennokki** [comment]
Good point i forgot to update the docs regarding file descriptors.

Meanwhile, check the benchmarks section: https://docs.soketi.app/benchmarks

**Comment by lechatthecat** [comment]
@rennokki 
Thank you for the benchmarks. It seems the performance is good up to 1000 users.
But I still don't know what is the max concurrent connections. I looked at this website: 
https://alexhultman.medium.com/millions-of-active-websockets-with-node-js-7dc575746a01#:~:text=The%20theoretical%20limit%20is%2065k,*%2020k%20%3D%201%20mil).

And this website says maybe 1 million connections is the practical max number after tweaking the file descriptor. 
> The theoretical limit is 65k connections per IP address but the actual limit is often more like 20k, so we use multiple addresses to connect 20k to each (50 * 20k = 1 mil).

So my guess is that the max concurrent connections that soketi can handle per instance is similar number and this can be increased by horizontal scaling.
