### ISSUE TITLE
4301 The app does not have client messaging enabled.

### ISSUE THREAD

**Issue by miladhspr** [soketi/soketi#572]
Im using chatify and I decided to switch from pusher to soketi.
but I get multiple error like:
* ["Error: JSON returned from auth endpoint was invalid, yet status code was 200. Data was: "]
* ["No callbacks on private-chatify for pusher:subscription_error"]
* ["No callbacks on presence-activeStatus for pusher:subscription_error"]
* [code":4301,"message":"The app does not have client messaging enabled.]

**Comment by rennokki** [comment]
You need to open up the developer tools and see your WS requests and what's being transmitted. 

Most of the options are being disabled in Soketi. You should seek for the app settings: https://docs.soketi.app/app-management/array-driver
