### ISSUE TITLE
Any Debug Dashboard?

### ISSUE THREAD

**Issue by aneesdev** [soketi/soketi#584]
Hi @rennokki,

First of all thanks for this great library ❤️. I wanted to ask is there any chance for a Debug Dashboard like one in beyondcode/laravel-websockets?

Like this one:

![image](https://user-images.githubusercontent.com/92947803/177278348-de3358de-3db6-4519-a631-f5f8234ee2f1.png)

Also it will be great if you can provide the Debug Dashboard also in your cloudflare workers serverless soketi service. as we are using it and it is just ❤️.

Thanks,
Anees

**Comment by rennokki** [comment]
Currently working on one based on my time. 😬 Will be released as soon as possible.

**Comment by vesper8** [comment]
Can't wait for this @rennokki, this is the only thing that's stopping me migrating from Laravel Websockets at this point.

Thanks for your continued hard work!

**Comment by luchtech** [comment]
Thanks for creating this, @rennokki !

I have added this to my Docker setup. Hopefully, we can have a Debug Dashboard soon but no rush! ✨
The Debug Dashboard is more of an additional tool for peer-to-peer explanations. 😇
