### ISSUE TITLE
PusherSwift SDK can't connect to the Cloudflare worker.

### ISSUE THREAD

**Issue by EricSKCheng** [soketi/soketi#585]
I follow the example from the Soketi dashboard:

`let options = PusherClientOptions(
  host: .host(""),
  port: .port(443),
  useTLS: .useTLS(true),
  autoReconnect: .autoReconnect(true)
)
let pusher = Pusher(key: "", options: options)
pusher.connect()`

But I can't connect to the worker with the error message: 
`"Pusher: [PUSHER DEBUG] Websocket received error. Error: POSIXErrorCode(rawValue: 53): Software caused connection abort"
`

**Comment by rennokki** [comment]
Hi there. The Swift SDKs are not entirely known by me how they work, so I'll be happy to know how these messages can be debugged.

**Comment by emadsaber2024** [comment]
Issue solved with me after downgrading Pusher SDK 8.0.0. 
Problem only exists on versions after 8.0.0.
