### ISSUE TITLE
[Bug] Docker Environment Variable for Webhooks

### ISSUE THREAD

**Issue by trocker** [soketi/soketi#614]
The environment variable in docker run for webhooks SOKETI_DEFAULT_APP_WEBHOOKS takes the passed argument as a string instead of JSON. I believe this bug causes "hasClientEventWebhooks" remain false and nothing gets called on the webhook. 

This is what I'm using for the docker setup: 
`docker run -p 6001:6001 -p 9601:9601 -e "SOKETI_DEFAULT_APP_WEBHOOKS=[{'url': 'https://httpdump.io/re1sah', 'event_types': ['client_event']}]" -e SOKETI_PORT=6001 quay.io/soketi/soketi:1.0-16-debian`

**Comment by rennokki** [comment]
The string is not a valid JSON if the keys and values contain `'` instead of `"`. You'd want to do this:

```bash
docker run -p 6001:6001 -p 9601:9601 -e SOKETI_DEFAULT_APP_WEBHOOKS='[{"url": "https://httpdump.io/re1sah", "event_types": ["client_event"]}]'
```

**Comment by trocker** [comment]
@rennokki - I've tried all combinations of `'` and `"` around different parts (including the one you've suggested). All the combinations are being taken in the docker container as a string and the "hasClientEventWebhooks" is always false.

Is there a way for you to confirm this by running the docker run command I've pasted above?
