### ISSUE TITLE
channel_vacated webhook should not be trigger when user is still connected to the channel

### ISSUE THREAD

**Issue by L3o-pold** [soketi/soketi#616]
Using multiple soketi instance (horizontal scaling), we see that `channel_vacated` event is trigger even if users are still connected to the channel.

Run two soketi instance and one redis.

```shell
docker run -d -p 6379:6379 redis:6.2.7
SOKETI_PORT=6001 node bin/server.js start --config=config.json 
SOKETI_PORT=6002 node bin/server.js start --config=config.json   
```

Use this config sample

```json
{
  "debug": true,
  "port": 6001,
  "mode": "full",
  "adapter": {
    "driver": "redis",
    "redis": {}
  },
  "appManager.array.apps": [
    {
      "id": "app-id",
      "key": "app-key",
      "secret": "app-secret",
      "webhooks": [
        {
          "url": "http://localhost",
          "event_types": ["channel_vacated"]
        }
      ]
    }
  ],
  "rateLimiter": {
    "driver": "redis",
    "redis": {
      "redisOptions": {}
    }
  },
  "database": {
    "redis": {
      "host": "127.0.0.1",
      "port": 6379
    }
  }
}
```

Create a two html file to test websocket:

The first one (index.html) to connect on the soketi port 6001.

```
<html>
<head>
    <title>test</title>
    <script src="https://js.pusher.com/7.0.3/pusher.min.js"></script>
</head>
<body>
    <script type="text/javascript">
        let client = new Pusher('app-key', {
            wsHost: '127.0.0.1',
            wsPort: 6001,
            forceTLS: false,
            encrypted: true,
            disableStats: true,
            enabledTransports: ['ws', 'wss'],
        });

        client.subscribe('benchmark').bind('timed-message', (message) => {
            console.log(message);
        });
    </script>
</body>
</html>
```

The second one (index2.html) with the same content except for the `wsPort` that should be change from 6001 to 6002.

Open two browser tab, one on index.html and the other one on index2.html.

Close one on the two tab and check soketi logs. You'll see that the `channel_vacated` webhook was triggered even if a user is still listening on the channel `benchmark`.

**Comment by L3o-pold** [comment]
Timeout reached while waiting for response in type 6. Forcing resolve with the current values.

this error message should not help

**Comment by L3o-pold** [comment]
I think due to the lack of `requestsTimeout` in the config, the request timeout right after being sent.

**Comment by rennokki** [comment]
Yeah, just figured out that the remaining connections go through the appropriate local or horizontal adapter.
