### ISSUE TITLE
Need help to reproduce benchmark result

### ISSUE THREAD

**Issue by soloradish** [soketi/soketi#617]
We are looking for a Pusher-compatible service to replace our Slanger service.
Before doing the full replacement we need to do some benchmark tests on both Soketi and Slanger side. 
Could you give some hint or guide that how you setup and do the benchmark tests? 

Any helps would be appratiated ^-^

**Comment by rennokki** [comment]
You have a list of steps to test with [k6](https://k6.io/) if you want: https://github.com/soketi/soketi/blob/1.x/.github/workflows/benchmark.yml

**Comment by soloradish** [comment]
I will share my benchmark result after I done this.
