### ISSUE TITLE
Cluster: Timeout reached while waiting for response in type 5. Forcing resolve with the current values.  

### ISSUE THREAD

**Issue by billypap1** [soketi/soketi#618]
I have connected 2 nodes (1 Master - one Slave) with cluster mode. 
When I start the Master node (1) and connect the second one, I get "New node added." -> "New master."  So 2 is the new master.

My issue: when i connect to first master node (1), I get this error: "Timeout reached while waiting for response in type 5. Forcing resolve with the current values. " when it tries to "sent message to other instances". The other node (2) which is the new master, never gets the new messages. 

My command: 

`SOKETI_ADAPTER_DRIVER=cluster SOKETI_CLUSTER_HOST=xxx.xxx.xxx (Public IP)  SOKETI_CLUSTER_BROADCAST_ADDRESS=xxx.xxx.xxx (private VPC address)  soketi start --config=/etc/soketi/config.json
`

PS.Q I don't have activated any firewall.

Is this a bug?

**Comment by rennokki** [comment]
It should be a problem with the networking or one of the servers not responding. If the request to other nodes timeouts, then it returns an error.
