### ISSUE TITLE
WSL, Sail and Flutter plugin: web_socket_channel 2.2.0 compatibility?

### ISSUE THREAD

**Issue by TylerByte666** [soketi/soketi#624]
Hi all.

I would really love to know how to get this working locally with Flutter: web_socket_channel 2.2.0 and Sail.

I have tried [soketi]("https://docs.soketi.app") locally through sail but I keep getting this flutter debug output: 
```debug
WebSocketException: Connection to 'http://10.0.2.2:6001#' was not upgraded to websocket
```

I use web_socket_channel 2.2.0 with flutter and have this as my home widget, where the error originates:

```dart
class _MyHomePageState extends State<MyHomePage> {
  final _channel = IOWebSocketChannel.connect(
    Uri.parse('ws://10.0.2.2:6001'),
  );

  @override
  initState() {
    _channel.sink.add(json.encode({
      "event": "pusher:subscribe",
      "data": {"channel": "channel"}
    }));

    _channel.stream.listen((_data) {
      print(_data.toString());
    }, onError: (error) {
      print("Socket: error => " + error.toString());
    }, onDone: () {
      print("Socket: done");
    });

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
          ],
        ),
      ),
    );
  }

  @override
  void dispose() {
    _channel.sink.close(status.goingAway);
    super.dispose();
  }
}
```
I use WSL, Docker-Desktop and Windows 10. The channel I want to connect to is public and is called: `channel`, the event is called: `App\Events\TestEvent.php`

I have added http ability in the `android/app/main/AndroidManifest.xml`:

```xml
<application
       ...
        android:usesCleartextTraffic="true" >
```
The web sockets are working with Vue.js, Echo.js and Pusher.js so I really do not know what to do. Please help. I have also used the pusher_client and pusher_channels flutter plugins🤕

**Comment by rennokki** [comment]
Soketi is meant to be used with the Pusher SDKs. I cannot offer support in this case.

**Comment by TylerByte666** [comment]
My fault, I do apologize. Thank you.

**Comment by ceojazzy** [comment]
I am using Pusher sdk in flutter but it says 
socket error: App key cbtv4fm7acbba45858uozlw4pvmrcezd not in this cluster. Did you forget to specify the cluster?
what is my cluster will be if i deploy it on railway.app?
Thanks
