### ISSUE TITLE
error with soketi with supervisor on EC2

### ISSUE THREAD

**Issue by RabieAli95** [soketi/soketi#672]
I'm trying to run soketi with supervourser 

I did all step but when I check the supervisorctl status I got this error:

```
$ sudo supervisorctl status
soketi:soketi_00                 BACKOFF   can't find command 'soketi'
```

Even I install soketi on my server (EC2) and when I run it `soketi start` it runs just fine!

my `soketi.ini`

```
[program:soketi]
process_name=%(program_name)s_%(process_num)02d
command=soketi start
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=ec2-user
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/soketi-supervisor.log
stopwaitsecs=60
stopsignal=sigint
minfds=10240
```

**Comment by kentlee87** [comment]
Is this fixed? I m facing the same issue. I can't make it work in supervisord...

**Comment by kentlee87** [comment]
By the way, I resolved it by using pm2 process manager rather than supervisor.
It just work perfectly fine.
$ pm2 start soketi -- start --config=/your-config-file.json
