### ISSUE TITLE
Error while use Soketi in production

### ISSUE THREAD

**Issue by RabieAli95** [soketi/soketi#673]
I just deployed Soketi on EC2 with all its things (SSL, config Nginx proxy and etc) and I got a response in my domain (OK) which returns from Soketi so I assume all things are just fine! the domain (realtime.my_doamin.co). I connected with the client side and the Network is:
<img width="1373" alt="Screen Shot 2022-08-25 at 9 09 25 AM" src="https://user-images.githubusercontent.com/89542037/186588136-2587fd4f-027c-49ae-bab0-d77ae6337dd7.png">

On the server-side I got a weird error:
 ```
Pusher error:.
```
Full error: https://ibb.co/FJpnKs2

Here is the way I used it with Laravel:

in `.env` file
```
PUSHER_APP_KEY=app-key
PUSHER_APP_ID=app-id
PUSHER_APP_SECRET=app-secret
PUSHER_HOST=realtime.my_doamin.co
PUSHER_PORT=80
```

in `bootstrap.js` file:
```js
window.Echo = new Echo({
    broadcaster: "pusher",
    key: "app-key",
    wsHost: "realtime.my_doamin.co",
    wsPort: 80,
    wssPort: 443,
    forceTLS: "https",
    enabledTransports: ["ws", "wss"],
});

window.Echo.channel("orders").listen("OrderStatusUpdated", (e) => {
    console.log(e);
});
```

In `config/broadcasting.php` file:
```
'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY', 'app-key'),
            'secret' => env('PUSHER_APP_SECRET', 'app-secret'),
            'app_id' => env('PUSHER_APP_ID', 'app-id'),
            'options' => [
                'host' => env('PUSHER_HOST', '127.0.0.1'),
                'port' => env('PUSHER_PORT', 6001),
                'scheme' => env('PUSHER_SCHEME', 'http'),
                'encrypted' => true,
                'useTLS' => env('PUSHER_SCHEME', 'https') === 'https',
            ],
        ],
```

In `OrderStatusUpdated.php` file:

```php
class OrderStatusUpdated implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public function __construct(public $id)
    {
    }

    public function broadcastOn()
    {
        return new Channel('orders');
    }
}
```

in `web.php` file:
```php
class Order
{
    public function __construct(public $id)
    {
    }
}

Route::get('/', function () {
    return view('welcome');
});

Route::get('/test', function () {
    OrderStatusUpdated::dispatch(new Order(1));

    return 'Event has been sent!';
});
```

I think there is a problem with SSL on the server side in the Laravel project.

I used Certbot to install SSL for the Soketi server

[Here](https://docs.soketi.app/getting-started/ssl-configuration) in docs SSL I did not do anything like it! Should I?

**Comment by DarkGhostHunter** [comment]
Almost the same here. No error though.

Soketi works, Laravel pushes the event through one of the workers, but Soketi does not return it to the front end, like it never received something to push.

**Comment by RabieAli95** [comment]
@DarkGhostHunter Beside the above issue I've got the same issue with no receiving data in frontend!

**Comment by DarkGhostHunter** [comment]
I fixed it. It was using “app-secret”. Soketi received the payload, but didn’t push it because the secret was incorrect, even if the whole payload is correctly signed.

Check with debug if there is a payload received by soketi. You may have your app secret wrong. Side note: all ENV keys for the soketi process must be appended  with ”SOKETI_”, otherwise the process won’t pick them up. I learned the hard way using the docker installation. 

Italo Baeza C.

**Comment by RabieAli95** [comment]
@DarkGhostHunter NICE! 
just a question pls, how did you install the SSL on your server? and is there anything I have to config with Soketi after installing SSL on the server? 

I just installed SSL by Certbot I do not know whether this is the right or wrong way!

**Comment by RabieAli95** [comment]
@DarkGhostHunter  How to check with debugging if Soketi receives a payload? I'm not using docker

**Comment by RabieAli95** [comment]
@DarkGhostHunter  How to check!

<img width="505" alt="Screen Shot 2022-08-27 at 2 40 23 PM" src="https://user-images.githubusercontent.com/89542037/187028580-fd90b6a7-bb9d-4412-b7b6-6b1729b8186f.png">
<img width="495" alt="Screen Shot 2022-08-27 at 2 40 15 PM" src="https://user-images.githubusercontent.com/89542037/187028583-ecd237e3-b5eb-4838-a358-52cef128ec38.png">

**Comment by DarkGhostHunter** [comment]
I'm using a load balancer / proxy in front. SSL config is in the documentation. From there your on your own, but as far as I remember certbot saves the SSL certificates and keys somewhere, you just have to find them. From there you're on your own. I recommend you investigate using a load balancer or proxy instead of manually configuring SSL for each app and domain, like Traefik or Caddy. 

To debug Soketi you need to use `SOKETI_DEBUG=1`. The debug information will be shown on the process output, not on the WebSockets connection.

**Comment by RabieAli95** [comment]
@DarkGhostHunter  Pls I got confused with config Soketi with  SSL

I need to create a JSON config file and put these into the file
```
SOKETI_SSL_CERT
SOKETI_SSL_KEY
SOKETI_SSL_PASS
SOKETI_SSL_CA

```
 then run `soketi start --config=/path/to/config.json` to that config. Is that right?

**Comment by DarkGhostHunter** [comment]
You may hire someone to do that for you if it seems too difficult to configure.
