### ISSUE TITLE
[request] Listen to event on server side

### ISSUE THREAD

**Issue by ajaybhargav** [soketi/soketi#674]
Hi, Is there a way to listen to client events on server side?
e.g. client connected or client left the channel etc.

 I am using Laravel. I need to take some action on server when client closes the connection. I see webhooks but I am unsure if it is what I need, and there is no example of how to implement it.

Thanks!

**Comment by ajaybhargav** [comment]
Something like this https://github.com/beyondcode/laravel-websockets/issues/217

**Comment by rennokki** [comment]
Webhooks: https://docs.soketi.app/advanced-usage/app-webhooks

**Comment by ajaybhargav** [comment]
Thank you so much for guiding. It took me some time to get hold of it :)
i think documentation can be improved.

I am able to get events, I have also enabled client events, and I am trying to generate custom client event. I am sure I am not using the right way to fire custom event.

currently I am doing this:

``` js

  window.Echo.connector.pusher.send_event('client-command', {
      'command': command
  });

```

It is getting received on server

``` bash
[Fri Aug 26 2022 20:56:53 GMT+0530 (India Standard Time)] ⚡ New message received:   
{
  message: {
    event: 'client-command',
    data: { command: 'test' }
  },
  isBinary: false
}
```

But does not reach client webhook, even though webhooks are enabled and working for other hooks.

It reaches upto this point

https://github.com/soketi/soketi/blob/9f85846febf1953ea3adde7a8c60ebf25cc3eb8e/src/ws-handler.ts#L589

canBroadcast is false which is an indication I am not sending event correctly. So can you please help me guide the right way to fire event from browser?

**Comment by ajaybhargav** [comment]
Sorry to bother... 🙏🏼 
`client.whisper()` the right answer
