### ISSUE TITLE
[BUG] Environment variables not working in docker container

### ISSUE THREAD

**Issue by KarimJedda** [soketi/soketi#675]
**Description**
Mainly missing documentation / unexpected behavior. 

**Reproduction steps**
`docker run -it -p 6001:6001 -p 9601:9601 -e DEFAULT_APP_ID="soketi" -e DEFAULT_APP_KEY="soketi" -e DEFAULT_APP_SECRET="soketi" -e SOKETI_DEBUG=1 quay.io/soketi/soketi:1.0-16-debian`

```
{
  adapter: {
    driver: 'local',
    redis: {
      requestsTimeout: 5000,
      prefix: '',
      redisPubOptions: {},
      redisSubOptions: {},
      clusterMode: false
    },
    cluster: { requestsTimeout: 5000 },
    nats: {
      requestsTimeout: 5000,
      prefix: '',
      servers: [ '127.0.0.1:4222' ],
      user: null,
      pass: null,
      token: null,
      timeout: 10000,
      nodesNumber: null
    }
  },
  appManager: {
    driver: 'array',
    cache: { enabled: false, ttl: -1 },
    array: {
      apps: [
        {
          id: 'app-id',
          key: 'app-key',
          secret: 'app-secret',
          maxConnections: -1,
          enableClientMessages: false,
          enabled: true,
          maxBackendEventsPerSecond: -1,
          maxClientEventsPerSecond: -1,
          maxReadRequestsPerSecond: -1,
          webhooks: []
        }
      ]
    },

```

Seems the arraymanager is hardcoded here: https://github.com/soketi/soketi/blob/9d4fbb2839122c72734099f884a2b92c374769dd/src/cli/cli.ts#L61 and there's no way to override that with an environment variable. 

**Expected behavior**
Expected would be either:
- update the documentation with the mention that the only way to override values is through JSON
- Override local variables with environment provided ones

**Comment by rennokki** [comment]
Prefix the variable names with `SOKETI_`

**Comment by DarkGhostHunter** [comment]
This should be documented.

**Comment by Chris1234567899** [comment]
Please update the docs. Was looking for this for weeks...

**Comment by DarkGhostHunter** [comment]
> Please update the docs. Was looking for this for weeks...

https://github.com/soketi/docs/pull/17
