### ISSUE TITLE
[BUG] curl http://127.0.0.1:9601/metrics returns empty reply from server

### ISSUE THREAD

**Issue by oxytoxin** [soketi/soketi#689]
![image](https://user-images.githubusercontent.com/61694153/189281638-fe84087e-7a8f-4c82-bd67-8990ca17ee82.png)

.env config

![image](https://user-images.githubusercontent.com/61694153/189281767-df79a548-b066-4e73-9cce-3f829ed525af.png)

**Comment by oxytoxin** [comment]
closing as it was due to env variables not correctly set up. thanks

**Comment by muuvmuuv** [comment]
Hey, how exactly are your variables set now? I am using supervisorctl and have set `environment=SOKETI_METRICS_ENABLED=1` but still getting the same response.

**Comment by muuvmuuv** [comment]
Ok, I had to set it in the config json `"metrics.enabled": true,`
