### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by radudalbea** [soketi/soketi#709]
**Description**
Doesn't work with pusher SDK.

**Reproduction steps**
I am using soketi with Docker. The container is the one from the official docs. 
On the server(nodejs) I am connecting to the soket using Pusher. The code is like this

const pusher = new Pusher({
      appId : 'some-id',
      key   : 'app-key',
      secret: 'some-app-secret',
      host  : '127.0.0.1',
      port  : '6001'
    });

On the client I am still using Pusher and I'm connecting to the socket with this:

const client = new PusherJS('app-key', {
      wsHost           : '127.0.0.1',
      wsPort           : 6001,
      forceTLS         : false,
      disableStats     : true,
      enabledTransports: ['ws', 'wss']
    });

The problem is that when I try to trigger a message from the server, the client for some reason does not get it.

The code is the following:
**Server**
pusher.trigger('chat-room', 'message', {
   message: 'hello world'
});

**Client** 
client
  .subscribe('chat-room')
  .bind('message', (message) => {
     console.log(message);
   });

**Environment**
Docker compose file

version: '3.9'
services:
  soketi:
    container_name: "soketi_server"
    restart: unless-stopped
    image: "quay.io/soketi/soketi:latest-16-alpine"
    ports:
      - "6001:6001"
      - "9601:9601"
    environment:
      - DEBUG=1
      - DEFAULT_APP_ID=some-id
      - DEFAULT_APP_KEY=app-key
      - DEFAULT_APP_SECRET=some-app-secret
      - HOST=127.0.0.1
      - PORT=6001
      - SCHEME=http # or https
      - METRICS_ENABLED=true
      - METRICS_SERVER_PORT=9601
    networks:
      - soketi_network

networks:
  soketi_network:
    driver: bridge

Another thing to mention is that if I use the same code with a pusher app, everything is working.

P.S. By the way the docs are a little unclear for the environment variables. This is what I found using multiple sources. You should explain somewhere very clear how they should look. I'm not clear if I should prefix them with SOKETI or not.

**Comment by rennokki** [comment]
You have to prefix the variables with `SOKETI_`
