### ISSUE TITLE
[BUG] Incorrect cache channel implementation

### ISSUE THREAD

**Issue by mlnkrish** [soketi/soketi#710]
**Description**
How the cache channel is supposed to work - https://pusher.com/docs/channels/using_channels/cache-channels/
The following is the soketi behaviour.
1) The soketi implementaion does not fire the pusher:cache_miss event when the cache is empty. Only the webhook is triggered.
2) The soketi implementaion fires the pusher:cache_miss event with cached value as data, when data is available in cache. Which is wrong, the pusher:cache_miss event should only be fired when data is unavailable in cache.
3) The soketi implementaion does not fire the last sent event on the cache channel when data is available in the cache.

**Environment**
- Soketi version : 1.4.16
- Adapter : redis
- App Manager : array
- Queue : sync
- Cache Managers : redis

**Additional Information**
The below are the parts of code which are causing the issue
https://github.com/soketi/soketi/blob/1.x/src/http-handler.ts#L377-L395
https://github.com/soketi/soketi/blob/1.x/src/ws-handler.ts#L698-L706

I'm happy to fix the issue and provide a pull request with tests. Could you tell me the branch against which I should write the fix.

Thanks

**Comment by rennokki** [comment]
Hi @mlnkrish,

The 1.x branch is for the current bugfixes. Before diving in, have you checked the tests: https://github.com/soketi/soketi/blob/1.x/tests/public.test.ts#L116-L151 and https://github.com/soketi/soketi/blob/1.x/tests/webhooks.test.ts#L575-L613 ?
