### ISSUE TITLE
Laravel 9 with Sail, Back-end Broadcasting failing, Echo front-end succeeds?

### ISSUE THREAD

**Issue by smcgovern** [soketi/soketi#757]
Hello, I'm currently trying to setup Soketi to work via a fresh Laravel 9 install and seem to be running into an issue when trying to get the backend to broadcast. I am attempting to do so on my `localhost` over port `6001` over just `http`, no SSL involved

Everything seems to be functioning properly on the front-end. I am able to get `Echo` to connect to the server, subscribe to a channel, and send ping/receive pongs, but when I attempt to have the back-end trigger an event it seems to fail to be able to connect to the server at all?

This is the response:
`Pusher error: cURL error 7: Failed to connect to localhost port 6001 after 0 ms: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:6001/apps/app-id/events?auth_key=app-key&auth_timestamp=1670821955&auth_version=1.0&body_md5=db1e1ee1e7151bb41beeb2c1e03bda0b&auth_signature=3daebed024d3f0b2a7333c61e313aaf44bba436ab18a374f5472bb3181afd100.`

My `broadcasting.php` config:

```
        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY', 'app-key'),
            'secret' => env('PUSHER_APP_SECRET', 'app-secret'),
            'app_id' => env('PUSHER_APP_ID', 'app-id'),
            'options' => [
                'host' => env('PUSHER_HOST', '127.0.0.1'),
                'port' => env('PUSHER_PORT', 6001),
                'scheme' => env('PUSHER_SCHEME', 'http'),
                'encrypted' => false,
                'useTLS' => env('PUSHER_SCHEME') === 'https',
            ],
        ],
```

and `.env`

```
PUSHER_APP_ID=app-id
PUSHER_APP_KEY=app-key
PUSHER_APP_SECRET=app-secret
PUSHER_HOST=localhost
PUSHER_PORT=6001
PUSHER_SCHEME=http
PUSHER_APP_CLUSTER=mt1
```

I feel like I'm missing something simple, amazing tool here. Thanks for your time.

**Comment by smcgovern** [comment]
Solved: The broadcasting.php config host shouldn't have been pointing at localhost, but rather the Docker service container name `soketi`.

**Comment by emmadesilva** [comment]
I'm having pretty much the exact same issue, but I'm using the NPM package, not Docker. The Curl response returns the following:

```
array:2 [
  "body" => false
  "status" => 0
]
```

Could it be related, or should I make a new issue?

Edit: I think I figured out my issue. Frontend works with SSL, backend does not work with SSL. My certificate is self signed. Doing `curl http://127.0.0.1:6001` without configuring Soketi to use the SSL certificate gives an `OK` response. When SSL is on, doing the same curl command gives an empty response.
