### ISSUE TITLE
Get count/list of current subscribers on public channels

### ISSUE THREAD

**Issue by mwargan** [soketi/soketi#786]
**Is your feature request related to a problem? Please describe.**
When joining a public channel, there is no way to know who is already in the channel unless each member emits its own client-event to inform everyone else of their presence.

**Describe the solution you'd like**
https://pusher.com/docs/channels/using_channels/events/#pushersubscription_count-1404026137 or even better would be to get back a list of connected socket-IDs in a channel.

**Describe alternatives you've considered**
Presence channels, but they require authentication and this is a purely public no-auth channel.

**Additional context**

**Comment by hailwood** [comment]
@mwargan  #819

**Comment by mwargan** [comment]
@hailwood super cool, thanks! I think we can close this one in that case ;)
