### ISSUE TITLE
[question] Is this project still maintained?

### ISSUE THREAD

**Issue by nathanaelytj** [soketi/soketi#823]
I want to ask @rennokki 

Is this project still maintained?

Thank you

**Comment by stayallive** [comment]
What is currently not working for you? Not all project stay super active with commits because there is not always much to do.

**Comment by nathanaelytj** [comment]
Everything working fine right now. I asked because I read issues, and PR and many of them left hanging and unanswered.
E.g PR for bump deps version from dependabot. I use dependabot myself and while I know that updating your deps require some testing, dependabot still useful to help our deps chain updated and help against possible security vulnerability in our deps chain.

So, what's this repo / project status?

**Comment by tinusg** [comment]
The product is solid but judging by the amount of Pull requests there indeed is significant interest in improving the project. As always, if you rely on this product you can always decide to sponsor @rennokki in order to show your support.
