### ISSUE TITLE
Setup Soketi on own domain (Laravel)

### ISSUE THREAD

**Issue by SimondeJong-VinvuSoftware** [soketi/soketi#842]
Dear Soketi,

I am trying to setup Soketi on it's own domain as a pusher replacement. I would prefer to setup Soketi as a separate service all my apps (Laravel) can connect to. However, I am having trouble setting this up correctly and would really appreciate some help. When trying to broadcast an event I get cURL error 7:
```
luminate\Broadcasting\BroadcastException: Pusher error: cURL error 7: Failed to connect to soketi.example-domain.com port 6002 after 31 ms: Couldn't connect to server
```

I have setup my config as follows:

```
{
   "debug": true,
   "port": 6002,
   "appManager.driver": "mysql",
   "database.mysql": {
      "user": "soketi",
      "password": "password",
      "database": "soketi"
   }
}
```

I start soketi by running the command `soket start --config=/home/soketi/config/soketi.json`. The path is correct to the config file. This is also evident from the debug information displayed when Soketi is started. I am using port 6002 as port 6001 is already taken by another service.

I am running this on an AlmaLinux 8.7 server using Virtualmin to manage the Apache and MariaDB servers. My apache config is set up as follows:
```
Listen 6002

<VirtualHost 85.10.151.116:6002>
	ServerName soketi.example-domain.com
        ServerAlias www.soketi.example-domain.com
    
	SSLEngine on
  	SSLProxyEngine on
  	SSLCertificateFile /etc/ssl/virtualmin/example/ssl.cert
  	SSLCertificateKeyFile /etc/ssl/virtualmin/example/ssl.key
  	SSLCACertificateFile /etc/ssl/virtualmin/example/ssl.ca

  	ProxyRequests on
  	RequestHeader set X-Forwarded-Proto "http"
  	ProxyPass /app http://127.0.0.1:6002/
  	ProxyPassReverse /app http://127.0.0.1:6002/

  	RewriteEngine on
  	RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
  	RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
  RewriteRule .* ws://127.0.0.1:6002%{REQUEST_URI} [P]
</VirtualHost>
``` 

This Apache config is based off a StackOverflow answer I found here:
https://stackoverflow.com/questions/74999631/how-do-i-configure-apache2-correctly-for-websockets-ssl-wss

I have also added port 6002 to my server firewall's open poorts (TCP).

My Laravel broadcasting.php is set to 
```
 'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY', 'app-key'),
            'secret' => env('PUSHER_APP_SECRET', 'app-secret'),
            'app_id' => env('PUSHER_APP_ID', 'app-id'),
            'options' => [
                'host' => env('PUSHER_HOST', '127.0.0.1'),
                'port' => env('PUSHER_PORT', 6001),
                'scheme' => env('PUSHER_SCHEME', 'http'),
                'encrypted' => true,
                'useTLS' => env('PUSHER_SCHEME') === 'https',
            ],
        ],
```
as per the Soketi documentation.

I feel the issue is most likely in my Apache / Server config, not my Laravel app. The Laravel app did work correctly when I was still connecting to Pusher. However, I am not sure of this and I am grateful for any help / tips given.

**Comment by rennokki** [comment]
"Couldn't connect to server" - most likely you are having firewall issues.

**Comment by SimondeJong-VinvuSoftware** [comment]
@rennokki , Thanks for the help. I was indeed a port not correctly opened in the firewall.

When setting up the Pusher SDK I did notice a sign error in the docs; 
```
const PusherJS = require('pusher-js');

let client = new PusherJS('app-key', {
    wsHost: '127.0.0.1',
    wsPort: 6001,
    forceTLS: false,
    encrypted: true,
    disableStats: true,
    enabledTransports: ['ws', 'wss'],
});

client.subscribe('chat-room').bind('message', (message) => {
    alert(`${message.sender} says: ${message.content}`);
});
```
(https://docs.soketi.app/getting-started/client-configuration/pusher-sdk)

When using this config (adjusted to my relevant key's, host and ports), I get an error that the pusher options requires a cluster. Therefore I would like to propose an update to the docs;
```
const PusherJS = require('pusher-js');

let client = new PusherJS('app-key', {
    wsHost: '127.0.0.1',
    wsPort: 6001,
    wssPort: 6001,
    cluster: 'soketi',
    forceTLS: false,
    encrypted: true,
    disableStats: true,
    enabledTransports: ['ws', 'wss'],
});

client.subscribe('chat-room').bind('message', (message) => {
    alert(`${message.sender} says: ${message.content}`);
});
```

This updated code includes a cluster and wssPort. 

Thanks again for the help! As my issue has been resolved I will close this issue.
