### ISSUE TITLE
[BUG] Unable to complete Cloudflare Credentials Soketi Serverless

### ISSUE THREAD

**Issue by leoboom-isme** [soketi/soketi#853]
After sign up in Soketi Serverless, it requested to create the Cloudflare Credentials.

After key in all the credentials and signed up for Workers Paid plan in Cloudflare, it still says

The account has not enabled access for Durable Objects. Enable them at:
https://dash.cloudflare.com/xxxxxxx/workers/overview?enable-durable-objects 

![image](https://github.com/soketi/soketi/assets/103731876/8fcf2b76-82b5-4426-af4a-acc2779f4d2b)

In the latest Cloudflare dashboard, the URL above doesn't exist anymore. And in the latest Cloudflare Paid plan for workers, Durable Objects is already enabled by default.

**Comment by the-line** [comment]
I have the exact same problem, I don't get it working in any way. With and without email address. also the link for enrolling durable object does not work.

**Comment by phrobix** [comment]
What did it for me was creating a dummy worker in cloudflare. I did the following:

- Create a `common worker examples`
- Complete everything
- Click on `configure worker`
- Scroll to the bottom and enable durable objects there
- Click `manage application`
- Delete the dummy project

Now you've enable durable objects and you can complete the signup.

**Comment by the-line** [comment]
the solution of @phrobix is working! thank you

**Comment by daweth** [comment]
@phrobix worked for me as well
