### ISSUE TITLE
[BUG] Release 1.5 broke docker image ARM Support

### ISSUE THREAD

**Issue by sneycampos** [soketi/soketi#855]
**Description**
Can't run 1.5 on ARM server

**Reproduction steps**
1. Connect on a ARM Server
2. deploy using Docker (https://docs.soketi.app/getting-started/installation/docker)
3. See error

**Expected behavior**
like 1.4 version

**Environment**
- Soketi version 1.5 
- Adapter (local, redis): redis
- Queue (sqs, redis, sync): redis

**Screenshot**
![image](https://github.com/soketi/soketi/assets/585263/5a215f2d-204d-42a2-be8e-dd691aa0185b)

**Comment by sneycampos** [comment]
> I am running it without Docker, that seems to work.

Can you share your arm server specs? What processor?

**Comment by roelvan** [comment]
I am using ARM64 (ampere altra) from Hetzner:Truly thrifty cloud hostinghetzner.comOn Jun 14, 2023, at 10:54 AM, Silvio Ney ***@***.***> wrote:﻿

I am running it without Docker, that seems to work.

Can you share your arm server specs? What processor?

**Comment by sneycampos** [comment]
> I am using ARM64 (ampere altra) from Hetzner:Truly thrifty cloud hostinghetzner.comOn Jun 14, 2023, at 10:54 AM, Silvio Ney ***@***.***> wrote:﻿ I am running it without Docker, that seems to work. Can you share your arm server specs? What processor? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

Thank you, i will test with Hetzner, i am using Oracle's arm

**Comment by roelvan** [comment]
I used these instructions (installed it as a good ol' node js app):

https://docs.soketi.app/getting-started/installation/cli-installation

**Comment by sneycampos** [comment]
> 

Tried in hetzner with Cloud Shared vCpu (Arm64 Ampere Altra) and does not works

**Comment by roelvan** [comment]
I am not a Soketi member/developer, just a user.
It 100% works on my ARM64 Ampere Altra instance following the deployment instructions I mentioned earlier. So this is not a Soketi related bug or issue.
I suggest you seek help on the Soketi Discord on how to deploy Soketi correctly, be sure to mention your logs/errors and installation steps.
As for Docker, I would not know, I never deploy things with Docker.

**Comment by sneycampos** [comment]
Ok thanks

**Comment by sneycampos** [comment]
> I am not a Soketi member/developer, just a user. It 100% works on my ARM64 Ampere Altra instance following the deployment instructions I mentioned earlier. So this is not a Soketi related bug or issue. I suggest you seek help on the Soketi Discord on how to deploy Soketi correctly, be sure to mention your logs/errors and installation steps. As for Docker, I would not know, I never deploy things with Docker.

FYI: first of all, thank you for your time. 
I just noticed this problem only happens when using the docker image, when you have it installed with NPM it works fine.

I'm reopening the issue to docker image

**Comment by rennokki** [comment]
`1.5.0` broke it accidentally, but `1.6.0` fixed it. I will close it for now and feel free to re-open in case this is still not working.
