### ISSUE TITLE
[BUG] cache_miss event is only returned after hydrating the cache

### ISSUE THREAD

**Issue by chrispage1** [soketi/soketi#933]
**Description**

I've been testing the `cache-` prefix as I can really see a good use case for this. This is documented by Pusher (https://pusher.com/docs/channels/using_channels/cache-channels/)

Soketi, in contract with the documentation above:

- does not fire `pusher:cache_miss` when there is no cached data
- When there is a cache, it is emitted as a `pusher:cache_miss` event rather than the original event name

![image](https://github.com/soketi/soketi/assets/2487374/970137bc-a7c5-471e-8d23-c3eba6eae109)

This means, that to effectively use the cached channels, I'd need to listen for the `pusher:cache_miss` event to retrieve cached data, JSON decode that data and process it in the same way I would the standard event, and a separate listener for the event itself.

Is this intended behaviour or have I come across a slight spec mismatch?

Thanks,
Chris.

**Comment by rennokki** [comment]
Gonna be fixed in #723
